### ISSUE TITLE
useHover doesn't fire when component is mounted

### ISSUE THREAD

**Issue by ecumene** [pmndrs/use-gesture#162]
The `useHover` hook is not fired when the component is first mounted, and a mouse is within the components bounds. 

**CodeSandbox:** https://codesandbox.io/s/charming-forest-f1cjv

I know this might be a little bit of a challenge, and I'm happy to make a PR if required 😄

**Comment by ecumene** [comment]
After skimming the codebase, it wouldn't be too hard to fix this by adding an option to the generic config (or by default) to enable `hovering` on `mouseover` events. Thoughts on this?

**Comment by dbismut** [comment]
Hi! I hadn’t thought of this but you’re right, could be useful. You mean setting hovering on `mousemove` events right?

**Comment by ecumene** [comment]
That's correct! I have a hack in my code currently, where `mousemove` sets hovering to true. But that doesn't fit the case where the mouse is on the element, but doesn't move at all...

The only thing I can think to go further is to perhaps use a ref to calculate if you're in those bounds, set hovering to true if you are, except asking users to bind a ref along with `{...bind()}` is a lot haha

So would you prefer it be:
1. Default
2. A `useHover` specific config?

**Comment by dbismut** [comment]
It could be relatively simple to set `hovering: true` and trigger `onHover` when the mouse moves if the gesture wasn't active already, but it wouldn't solve the problem with the mouse not moving when the component mounts and it's fairly easy to do in user land.

At the end of the day this lib shouldn't try to hack the behavior of native handlers. `onMouseEnter` is only triggered when the mouse enters the component, and that's how it's designed. This is an edge case I believe, but there's a solution here that you can try:

https://codesandbox.io/s/affectionate-wozniak-yn1i1?file=/src/App.js

**Comment by ecumene** [comment]
If you believe the definition of hovering should be only mouse enter / mouse leave events, by all means keep it how it is! My use case isn't everyone elses, for sure

However, hover could mean "this happens whenever the users cursor is over the element", which is confusing when it only really means "this happens when the users cursor *enters* / *leaves* the element". The docs do say it is enter and leave events, so you are certainly in the right to keep it that way, as well 😄 

Here is a simplified version of what I currently have in my app, it's the same as you posted except simpler because it doesn't check for the hover pseudo class (which is fine in my case, because onMouseOver events never fire before the onMouseLeave event meaning you never end with a dangling `hovering = true`)

https://codesandbox.io/s/stupefied-robinson-rfn6o

Great work on the library! Keep it up

**Comment by dbismut** [comment]
You’re right, using _hover_ as the action is confusing. It’s a CSS selector and from that perspective it should behave like it.

Since there’s a `domTarget` option, nothing would prevent the lib to check for the hover selector on the ref if that option is used. I just need to see how hacky this might be.

I’ll reopen the issue so that I can keep track of it. Thanks for the suggestion!

**Comment by ecumene** [comment]
Thanks for considering again 😆 

Why do you need to keep track of the `domTarget`?  In the codesandbox I showed how you can achieve very similar results by not only enabling the hover on `mouseenter` and `mouseleave` but also `mouseover`

Is there a benefit to reading the DOM like that? I feel like it's bad practice to rely on refs for this purpose because the `:hover` pseudoclass could be disabled with a CSS pointer events disable.

**Comment by dbismut** [comment]
But unless I'm missing something, `hovering` doesn't become true in your sandbox? You need to exit the cursor and move it back in?

**Comment by ecumene** [comment]
![image](https://user-images.githubusercontent.com/6249465/79469929-5b076c80-7fdb-11ea-80a5-2b12193e8ea3.png)
My bad, I used the wrong event. `mousemove` works

(In my defense, `moseover` worked a couple of times for me)

**Comment by dbismut** [comment]
So `mousemove` will work but won't make it if the component mounts from under. In your case you might as well use `onMove` from `useGesture`.

`mouseover` is triggered every time the element **or a child element** is entered. So my guess is that you may have it triggered when you moved your mouse from the gray area to the text element or something like that.

I'm not sure about what to do next. There's a few options:

1. Do nothing and let people use `onMouseMove` as you just did 😅

2. Silently implement `mousemove` listeners when using `onHover`. This might be a bit of an overkill but that's acceptable.

3. Only if `onMove` and `onHover` are set by the user, trigger `onHover` when `mousemove` events are detected and `hovering` is set to false.

**Comment by ecumene** [comment]
I don't think option 2 is overkill, I think it would be a nice adjustment for this case. Sure it might add some complexity underneath, but that's what libraries are for... Am I right? 😆

IMO the current solution I have now is overkill since I have to export `hovering` to a state variable... It would clean up a lot of my code if `hovering` worked in this case

**Comment by dbismut** [comment]
Overkill in the sense that the current mouse move listener does some calculations about the mouse movement under the hood (velocity, distance) which are not needed for the purpose of just hovering, I'll see how to find the leanest way to achieve this.

**Comment by krispya** [comment]
I was running into this issue but in a slightly different scenario. I have popover menus inside a parent with hover styles that the user can cancel by hitting escape (or some other userland interaction that isn't pointer related) but the hover state remains stale on the parent since there was technically no pointerout event. 

https://user-images.githubusercontent.com/7064954/164951993-4f957e0d-4dfd-4c2f-9618-c27342faade5.mp4

I can get around the issue by implementing pointermove  on my side but I wanted to see if this was still something you were interested in implementing directly into use-gesture. I'd be willing to help!

**Comment by krispya** [comment]
I'm not sure why, but using `target` with a ref instead of spreading `bind` fixes this issue for me.

**Comment by dbismut** [comment]
Indeed. I'll close this, thanks for the tip!
