### ISSUE TITLE
Dragging objects while pointerlockcontrols is connected triggers error when using 8.1.0-beta.7 or 8 

### ISSUE THREAD

**Issue by snsie** [pmndrs/use-gesture#244]
**Describe the bug**
When testing 8.1.0-beta.7 or 8 I am receiving the error below when dragging objects while three's pointerlockcontrols is connected. 

```InvalidStateError: Failed to execute 'setPointerCapture' on 'Element': InvalidStateError```

The problem arises in the sandbox below after (1) pressing space to lock controls, then (2) dragging the floating box around. The box can be rotated without issue if pointerlockcontrols isn't connected.

**Sandbox or Video**
https://codesandbox.io/s/react-use-gesture-beta-test-lnkrb?file=/src/App.js

**Information:**
 - React Use Gesture version: v8.1.0-beta.8
 - OS: Ubuntu 20.04
 - Browser: tested on Chrome and Firefox

**Comment by dbismut** [comment]
Hi @snsie thanks for reporting this. I'll need to investigate further on what's the best strategy to address this but this is related to pointer lock (so THREE or r3f are not directly related). https://w3c.github.io/pointerevents/#setting-pointer-capture

**Comment by dbismut** [comment]
Should be fixed in latest beta (the next version is going to be abled v9 and not v8 as initially thought, given that there are so many breaking changes.

Here's an simple example with pointer lock: https://561b5.csb.app/

**Comment by snsie** [comment]
It's exciting to see the object responding to drag events while in pointer lock mode! The error that was causing the app to crash no longer exists. 

I updated the sandbox I originally posted via the next tag and there seems to be an issue in the latest beta. Clicking to drag the box while in pointer lock mode works as long as the cursor stays positioned over the object during the entire drag event. If you click to drag the box and your cursor leaves the box's position before the mouseup event fires, a few issues arise. 

The first is that the box won't respond to drag movements unless the cursor is actively hovering over it. Normally, the first mousedown event selects the box, then the cursor can be moved anywhere on the screen and the box will continue to rotate until the mouse button is released.

The second is that if the mouse button is released while not hovering the box, the mouseup event isn't triggered. As a result, hovering over the box again will cause it to rotate as if you were still holding the mouse button down. This behavior persists until you click on the box again to trigger the mouseup event.

The cursor offset is being set to the center of the screen in the sandbox I posted, so the circle reticle can be used to test these behaviors.

**Comment by dbismut** [comment]
I see... Indeed I fixed the use case where the element that requested pointer lock was the same that would receive the drag. But not when the pointer lock was requested by another element. In that case I would need to revert to the old behavior where I attach event listeners to the `window`. That sucks a bit but it's manageable.

**Comment by dbismut** [comment]
Hm... This is a bit harder than I thought, or at least it doesn't make a lot of sense in a DOM environment. As far as I understand, the only DOM element that can receive pointer events is the one that is being locked. That means that a drag can be initiated only if the locked element is the one you want to drag.

In r3f, the DOM element receiving events is always the `<canvas>`. But the meshes you want to interact with are targeted with raytracing, which is something unique to r3f. I'll need to investigate a bit more to see if the issue can be solved within r3f or within rUG.

**Comment by snsie** [comment]
Sounds good. Let me know if there is anything I can do that would be helpful to you.

One observation that is peculiar to me is when the pointer isn't locked, you can click an animated object and drag the cursor anywhere on the screen, even outside the chrome window, and the object will correctly respond to cursor movement. If the ```<canvas>```  is the only element receiving the events in r3f, why do objects respond to drag movements outside of the canvas?

**Comment by dbismut** [comment]
That's because useDrag sets pointer capture and r3f delegates that capture to the canvas (on top of some additional logic to virtually attach the pointer to the targeted mesh).

**Comment by dbismut** [comment]
Closing as fixed in v10 #300. Please let me know if the issue persists somehow.
