### ISSUE TITLE
Pinch not recognized when touches are from different target elements.

### ISSUE THREAD

**Issue by ThAlmighty** [pmndrs/use-gesture#278]
**Describe the bug**
Pinch is not working if both fingers are in a different div. For my project I have a canvas with tiles. The tiles should be individually clickable and the canvas as a whole pinchable / draggable. As long as a pinch is started with both fingers in the same tile, it works. When both fingers are in different tiles (but still in the canvas object) it doesn't.

Expected behavior would be that if the pinch gesture is set on a certain element, even tough the touches originate in different child elements, the gesture still executes perfectly (since two touches are happening in the element that has the gesture configured.

Diving in the code you can see that touches are retrieved from `targetTouches` in `getEventTouches`. If changed to `touches`, the behavior happens as expected.  Looking at the blame, there was a commit (https://github.com/pmndrs/react-use-gesture/commit/b11eda1470e3244918dc892e8974f07b3dcb851d) changing it from `touches` to `targetTouches` described as a fix. I could not find the reason for this or what it's fixing.

Maybe a possible fix is to make this behaviour configurable? 

**Sandbox**
Steps to reproduce:
- Trying pinching with one finger in the yellow, the other in the orange rectangle. Doesn't work where the expected behaviour would be that it does.

https://codesandbox.io/s/multi-gesture-card-forked-8ju7l?file=/src/styles.css

**Information:**
 - React Use Gesture version: v9.0.4
 - Device: OnePlus 8
 - OS: Android 11
 - Browser: Chrome

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Thanks a lot for the detailed issue, that's much appreciated. Indeed we need a fix here. 

If I remember correctly (my brain is a bit dusty), I used `targetTouches` so that you could have multitouch gestures on different elements at once and make sure events were attached to the right div.

I believe using `touches` would break that, or at least would require additional logic. 

Maybe we could test the `targetTouches` ancestors, but I'm not sure about the performance overhead if that happens on each frame. 

I'm on my phone atm and currently on holidays, so let me know if you want to have a shot at a PR, but make sure you test two pinches gestures at once on the two different elements.

**Comment by ThAlmighty** [comment]
Thanks for the quick response!

I don't think I fully understand the use case you described. I have a hard time to come up with reasons you'd want to have your touches filtered per child / target element when you define the hook on their parent. If you'd want to have specific behaviours for the child elements, you would preferably define the hooks on each of them as well?

Maybe I'm overlooking something here. I'd suggest we discuss it when you're back 😉  Enjoy your holidays!

**Comment by dbismut** [comment]
That's fine we can discuss, I'm not considering this as work ^^

Can you join the discord channel and ping me in there? It's easier for me to chat in Discord, we'll post the outcome of our conversation in GitHub once we agree.

**Comment by WinterCore** [comment]
Hey.

I hate to bother. but I think I might be having the same issue.

Any updates regarding this?

**Comment by dbismut** [comment]
@WinterCore sorry missed your message. I'm currently rewriting v10, and this is most definitely part of my todo list on most important fixes.

Have a look at this sandbox: https://codesandbox.io/s/gesture-pinch-5oq8x

cc @ThAlmighty

**Comment by dbismut** [comment]
Closing as fixed in v10 #300. Please let me know if the issue persists somehow.

**Comment by kutoman** [comment]
@dbismut great, thanks, it works for me

**Comment by awmleer** [comment]
I encountered the same problem with v9.1.3. May I ask is there any release schedule for v10?

**Comment by dbismut** [comment]
@awmleer you can use v10 as of now.

**Comment by awmleer** [comment]
@dbismut But it is still in beta. It is too risky for our project which has over ten thousands of users.

**Comment by dbismut** [comment]
Well releasing it is just me removing the beta tag from the version number :) It actually fixes a lot of bugs from v9. Try it in your app and give it a run see if anything breaks. The upgrading process won't be simpler when v10 is out of beta. But to answer your question, within a couple of weeks I'll make v10 official.

**Comment by awmleer** [comment]
@dbismut OK, I'll try it. Thanks a lot!
