### ISSUE TITLE
onHover does not fire while dragging

### ISSUE THREAD

**Issue by geordie2020** [pmndrs/use-gesture#280]
**Description**
When using useGesture with onDrag and onHover handlers, onHover does not get called while dragging. 

(It does not work either, when using useDrag and attaching onMouseEnter/onMouseLeave DOM event handlers manually.)

Related: #264 

**Sandbox**
[https://codesandbox.io/s/modest-cloud-2mq7q?file=/src/App.js](https://codesandbox.io/s/modest-cloud-2mq7q?file=/src/App.js)
Steps to reproduce: Drag from inside the element over its edges and you'll notice onHover does not fire.

**Information**
 - React Use Gesture version: [v9.1.3]
 - OS: MacOS
 - Browser Chromium 89.0

**Checklist**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
@geordie2020 Have a look at this! https://github.com/pmndrs/react-use-gesture/issues/264#issuecomment-827645944

**Comment by dbismut** [comment]
Closing as fixed in v10 #300. Please let me know if the issue persists somehow.

**Comment by hkalexling** [comment]
@dbismut Oops I am dumb I missed the `pointer.capture` part. Thanks!
