### ISSUE TITLE
onScroll direction sometime returns 0.999999 instead of 1 or -1

### ISSUE THREAD

**Issue by enheit** [pmndrs/use-gesture#290]
**Describe the bug**
Scroll direction sometimes triggers as 0.999999 instead of -1 or 1

Steps to reproduce:
- Open code sandbox example: https://codesandbox.io/s/infallible-pond-yhszv?fontsize=14&hidenavigation=1&theme=dark
- Open console
- Scroll the page

Current behavior:
- `directionY` prop sometime triggers as 0.999999

Expected behavior:
- `directionY` prop should always be either `-1` or `1` depending on scroll direction

**Sandbox or Video**
https://codesandbox.io/s/infallible-pond-yhszv?fontsize=14&hidenavigation=1&theme=dark

**Information:**
 - React Use Gesture version: ^9.1.3
 - Device: MacBook Pro 13 M1
 - OS: macOS Big Sur 11.1
 - Browser: Version 90.0.4430.72 (Official Build) (arm64)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I'll make sure to fix this in V10. I'll rely on `Math.sign`, so long IE.

**Comment by dbismut** [comment]
Closing as fixed in v10 #300
