### ISSUE TITLE
useDrag mouse right click handling

### ISSUE THREAD

**Issue by davischung** [pmndrs/use-gesture#301]
**Describe the bug**
Upon right click on a draggable item and dismiss the menu, the click persist with `down` true, and drags the item without physical clicking on mouse. It does not happen prior version 9.

**Sandbox or Video**
https://codesandbox.io/s/v364z

**Information:**
 - React Use Gesture version: v9.1.3
 - Device: N/A
 - OS: N/A
 - Browser: Chrome (Version 90.0.4430.212)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Oh nasty! I'll probably have to handle pointer cancelation. I'll fix that soon.
