### ISSUE TITLE
Click events seem to fire at the end of useDrag

### ISSUE THREAD

**Issue by moreguppy** [pmndrs/use-gesture#305]
**Describe the bug**
Click events seem to fire at the end of `useDrag`, even when `event.preventDefault` is being used?

Ideally I would like to have some draggable elements that contain links, and if the user only clicks (not drag), it should follow the link. Otherwise if they drag, the click event should not do anything at the end of the dragging.

Apologies if I haven't understood something around the events...

Thanks for your help.

**Sandbox or Video**
https://rrqgp.csb.app/

**Information:**
 - React Use Gesture version: latest
 - Device: Chrome, macOS, Macbook Pro

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
https://use-gesture.netlify.app/docs/options/#filtertaps-drag-only

**Comment by AlexisWalravens** [comment]
@moreguppy I have exactly the same situation, how did you managed to prevent the click to be fired at the end of the drag ?
As filterTaps only allows you to get the click event in the drag.
Thanks

**Comment by moreguppy** [comment]
@AlexisWalravens I've just updated my example sandbox with filterTaps option on and it seems to have resolved the click fired at the end of the drag: https://codesandbox.io/s/rrqgp?file=/src/App.js

Maybe the `event.preventDefault()` helps?

**Comment by HermannBjorgvin** [comment]
@moreguppy adding a `href` attribute leads to the same behavior as before, opens link after dragging.

**Comment by AlexisWalravens** [comment]
> @moreguppy adding a `href` attribute leads to the same behavior as before, opens link after dragging.

Yes, that's my issue.

@moreguppy Thank you for answering quickly though!

**Comment by dbismut** [comment]
@AlexisWalravens @HermannBjorgvin I'm think I can fix this, will release a fix attempt tonight in v10.

**Comment by dbismut** [comment]
Hi all, latest v10 beta should fix it. Here's the original sandbox working:

https://codesandbox.io/s/vigorous-kalam-mcgtj

The `onDragStart` handler on the `<a/>` tag is needed for Firefox, I don't know any other workarounds unfortunately.

**Comment by HermannBjorgvin** [comment]
@dbismut thank you!!!

![mvp](https://media.giphy.com/media/GVMhZwYv8U5NK/giphy.gif)

**Comment by MatthiasDunker** [comment]
Hey @dbismut ,
great work! I was looking for the exact same example a long while. Trying around with `eventOptions`, `domTarget` etc.
I can imagine this to be a quite common use case. Every slider which works as a teaser (blog articles for example).
I wonder if it does make sense to add it to the demo sandboxes.

**Comment by pierreburel** [comment]
Hey @dbismut, fyi this doesn't seems to work anymore on beta20 (worked on beta19) : https://codesandbox.io/s/condescending-feynman-xzthd

**Comment by dbismut** [comment]
@pierreburel dammit I knew this would break something. I'll add that usecase for test sandboxes and work on a fix.

**Comment by dbismut** [comment]
@pierreburel I've reverted the behavior to beta19 in beta21. Sorry about this...

**Comment by pierreburel** [comment]
No problem, it's a beta :) thanks for the quick answer!
