### ISSUE TITLE
Performance disparity between docs and actuality

### ISSUE THREAD

**Issue by mfbx9da4** [pmndrs/use-gesture#306]
**Describe the bug**
Drag examples in the docs such as [this one](https://use-gesture.netlify.app/docs/extras/) are extremely fast and map very accurately to my finger position. I've tried copying the examples one-to-one but there is a clear lag to catch up with my finger position.

[Here is an example](https://codesandbox.io/s/react-spring-gesture-basic-swipe-q47gf?file=/src/App.js:413-476) which has a clear lag when testing on iphone 12 on chrome. 

**Sandbox or Video**

https://codesandbox.io/s/react-spring-gesture-basic-swipe-q47gf?file=/src/App.js:446-475

**Information:**
 - React Use Gesture version: (I've tried all manner of combinations of versions with no impact but this is the configuration in the codesandbox)
```
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0",
    "react-spring": "9.1.2",
    "react-use-gesture": "9.1.3"
```

 - Device: IPhone 12 pro max
 - OS: [e.g. iOS14.5.1]
 - Browser chrome

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by mfbx9da4** [comment]
I combed through the source code of the examples. The issue was in fact with react-spring, I needed to supply `immediate: true` while the touch is active.

https://codesandbox.io/s/react-spring-gesture-basic-swipe-immediate-6bje9?file=/src/App.js

```
function PullRelease() {
  const [{ x }, api] = useSpring(() => ({ x: 0 }));
  const bind = useDrag(({ movement: [mx], down }) =>
    api.start({ x: down ? mx : 0, 
        immediate: down // the key line
    })
  );
  return (
    <animated.div {...bind()} style={{ padding: 40, background: "gold", x }}>
      Hello World
    </animated.div>
  );
}
```

**Comment by mfbx9da4** [comment]
I do however really think this should be included by default in the docs so I'm reopening

**Comment by dbismut** [comment]
Feel free to make a PR from the v10 branch and fix the docs in there!

**Comment by mfbx9da4** [comment]
Sure, hopefully will get round to it soon!

**Comment by dbismut** [comment]
Perfect thanks!
