### ISSUE TITLE
useGesture() does not rebind when domTarget changes

### ISSUE THREAD

**Issue by jwalton** [pmndrs/use-gesture#316]
**Describe the bug**

If you provide a `domTarget` to useGesture() and the target changes, useGesture() does not remove listeners from the old target and add them for the new target.

**Sandbox or Video**

https://codesandbox.io/s/use-react-gesture-remount-bug-p6sjo

If you mouse over the box in the middle, you'll see your mouse coordinates.  Click "Unmount" then "Mount", and mouse over the box, and your coordinates are gone.  :(

**Information:**
 - React Use Gesture version: v9.1.3.
 - Device: Desktop
 - OS: macOS 10.15.7
 - Browser: Firefox 88.0.1

**Comment by dbismut** [comment]
That's a hard one, I think v10 should solve this. Can you try `@use-gesture/react`?

**Comment by jwalton** [comment]
Well, I can tell v10 is trying to update the element, but it doesn't work out:

https://codesandbox.io/s/use-react-gesture-remount-bug-2-89sk5

If you click "unmount", it crashes because [element is undefined](https://github.com/pmndrs/use-gesture/blob/16aa66873f3747d999cbdb823bd92d3e854266a7/packages/core/src/EventStore.ts#L20).

**Comment by dbismut** [comment]
Ok thanks I'll have a stab at fixing this in the next couple of days.

**Comment by dbismut** [comment]
@jwalton should be fixed in latest v10 beta, let me know!
https://codesandbox.io/s/use-react-gesture-remount-bug-2-forked-nzvdk

**Comment by dbismut** [comment]
I tested this and it seems to work, so I'll close. Please comment if this doesn't solve it for you.

**Comment by jwalton** [comment]
Oh, sorry, I meant to comment on this.  Thanks for the quick turnaround!
