### ISSUE TITLE
Issue with initial position and drag using latest V10 beta

### ISSUE THREAD

**Issue by HermannBjorgvin** [pmndrs/use-gesture#319]
**Describe the bug**
Dragging and "from" property behaving strangely

I have this recent demo someone made with inertial scrolling, it works with "react-use-gesture" 9.2.1 and up but not with "@use-gesture/react" using the latest beta version.

https://codesandbox.io/s/react-spring-920-beta-touch-scrolling-example-forked-u8ul7?file=/src/App.js

**Information:**
 - Versions: see sandbox
 - Browser: Firefox

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
`from` should be used in conjunction with `offset`, not `movement` as it was the case in v9. This fixes a poor decision I made in v9 but it's a breaking change for sure.

**Comment by dbismut** [comment]
Indeed, separate issues, you had a problem in your spring config.

Here's the fix:
https://codesandbox.io/s/react-spring-920-beta-touch-scrolling-example-forked-ksoud
