### ISSUE TITLE
useGesture hook doesn't work in IE11 in v7

### ISSUE THREAD

**Issue by robatwilliams** [pmndrs/use-gesture#320]
**Describe the bug**
`useGesture` doesn't work at all in IE11. This is [due to using](https://github.com/pmndrs/use-gesture/blob/v7/src/hooks/useGesture.ts#L42) the `new Set(iterable)` variant of the Set constructor, which IE11 doesn't support - it ignores the argument.

This appears not to be an issue from v8 onwards.

**Information:**
 - React Use Gesture version: v7
 - Browser: IE11

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - n/a If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by robatwilliams** [comment]
Shared in case it helps anyone. Not an issue in newer versions, so closing.

**Comment by dbismut** [comment]
Thanks! Considering IE11 support has officially been dropped by Microsoft, use-gesture won't support it either.

**Comment by robatwilliams** [comment]
Expected and makes sense. Once we dig ourselves out of this technical/contractual hole we won't either.
