### ISSUE TITLE
altKey press of onWheel of ``useGesture`` is not working?

### ISSUE THREAD

**Issue by kousenlsn** [pmndrs/use-gesture#325]
**Describe the bug**
> altKey press of onWheel of ``useGesture`` is not working, always returns undefined.

![image](https://user-images.githubusercontent.com/14895129/123560100-b227d600-d776-11eb-9ab7-2899f4f02608.png)

**Information:**
 - React Use Gesture version: [e.g. v10.0.0-beta.14]
 - Device: MacBook pro
 - Browser: Brave, Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by dbismut** [comment]
Should be fixed in 10.0.0-beta.15, let me know!

**Comment by kousenlsn** [comment]
Sorry for the delay, I haven't had much time lately. But it seems it is still occurring

**Comment by kousenlsn** [comment]
https://codesandbox.io/s/alt-key-use-gesture10005-csx80

**Comment by dbismut** [comment]
It's `altKey` not `altkey`.

**Comment by kousenlsn** [comment]
Ops, my bad. 

I just tested it as ``altKey``, and indeed, it works on 10.0.0-beta.15+, and not on beta.14
