### ISSUE TITLE
Drag bounds not working dinamycally

### ISSUE THREAD

**Issue by danielx-art** [pmndrs/use-gesture#327]
**Describe the bug**
Using react three fiber I'm trying to make the camera move vertically as I drag the canvas, to simulate scrolling on canvas environment. I have a inferior and a superior limit in wich the camera has to stay inside, and I would like to use the rubberband property, and so I'm using bounds that should update if the camera position is at the superior limit, not letting the camera to go up further, or the inferior limit, not letting the camera go down further, but that doesn't seem to work at all, the camera act as if there's no bounds at all. What is going on? Is this intended/ not implemented yet or what am I missing?

**Sandbox or Video**
Here's a simple app, with a custom camera with its position-y controlled by the spring and the drag gesture, and a dodecahedron and ambient light just to visualize the 'scrolling'.
> https://codesandbox.io/s/use-gesture-test-i3n9o?file=/src/App.js

**Information:**
 - dependencies:
    "@react-spring/three": "9.2.3",
    "@react-three/drei": "7.0.6",
    "@react-three/fiber": "7.0.2",
    "@use-gesture/react": "10.0.0-beta.17",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0",
    "three": "0.130.1"
 - Device: PC
 - OS: Windows 10
 - Browser Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).
  - [X] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
@danielx-art haven't tried your sandbox, but bounds are only calculated when the gesture starts.

**Comment by danielx-art** [comment]
So it is impossible to use the rubberband effect on scrolling to final of a page, for example?

**Comment by dbismut** [comment]
Not sure I understand sorry. How is this impossible?

**Comment by danielx-art** [comment]
Oh I see, so if I understand you correctly and the bounds are calculated when the gesture starts, then I still can update those bounds on each drag gesture by using the initial coordinates of the gesture and their distance to the bounds. Going to test that this minute and I'll report back!

**Comment by danielx-art** [comment]
I was missing the fact that I can write bounds in terms of the canvas coordinates using transform exactly as they express in the documentation, but with flipped y to ensure the drag orientation. For some reason I believe that transform only worked if the bounds, even in canvas coordinates, would stay inside the viewport, I don't know why I tought that. I updated the sandbox to a version that works, if someone is interested:

https://codesandbox.io/s/use-gesture-test-i3n9o?file=/src/App.js

Thank you very much @dbismut, I'm closing this topic.

**Comment by dbismut** [comment]
I haven't done much 😅 glad you sorted this out!
