### ISSUE TITLE
PointerCapture set to Event Target

### ISSUE THREAD

**Issue by mtrifonov-design** [pmndrs/use-gesture#330]
Hello! 
I'm using use use-gesture in react, and I have the following issue:

I have a `<Parent />` component using the `useDrag` hook, within it I have a `<Child />` component.
As soon as the drag gesture starts, the `<Parent />` component changes state, and amongst other things, the `<Child />` component is unmounted. This appears to be causing bugs, and the drag gesture doesn't work as expected.

**Here's what I suspect is happening:**
After snooping around in the source code, it appears to me that react-use-gesture is using the `setPointerCapture` on the 
target of the `PointerDown` event that is fired as soon as the gesture begins. This event target, in my case, happens to be the element that is subsequently unmounted from the DOM, which seems to break things. My intuitive expectation would be that `setPointerCapture` ought to be set to the `ref` of the component I'm using the `useDrag` hook on.

These are, of course, just assumptions on my part. If anyone has an idea what might be going on, I'd be thankful to learn more.

**Comment by dbismut** [comment]
Hi. Can you please provide a sandbox?

**Comment by dbismut** [comment]
@mtrifonov-design I think I understand what's going on, I'll push a fix later today and you'll let me know how it works for you.

**Comment by dbismut** [comment]
Pushed 10.0.0-beta.20, let me know if this helps.

**Comment by mtrifonov-design** [comment]
@dbismut I tested the new version, and it works now. Thank you very much!

**Comment by dbismut** [comment]
Hey @mtrifonov-design I've reverted back to using `target` and not `currentTarget` as this used to break the behavior on iPhones (for some reason capturing from `currentTarget` doesn't work properly). If you need to unmount the `target` element try using the options: `{ pointer: { capture: `false` } }`. This will stop using `setPointerCapture` and rely on attaching events to the `window`. Sorry about this.

**Comment by mtrifonov-design** [comment]
@dbismut Alright, I will use the workaround then. Thank you for taking the time and informing me about this!
