### ISSUE TITLE
Gesture with wheel and drag bugs drag bounds.

### ISSUE THREAD

**Issue by danielx-art** [pmndrs/use-gesture#333]
### Discussed in https://github.com/pmndrs/use-gesture/discussions/329

<div type='discussions-op-text'>

<sup>Originally posted by **danielx-art** July  7, 2021</sup>
I have a canvas, and I want to move the camera down or up on the canvas, like scrolling a page, either by actually wheeling (useful on PC) or by dragging (to also be mobile friendly). If I wheel, I want the gesture to clamp at the page beginning or end, and If I drag, I want it to be a little rubberband effect on the same page limits.
Now if I only wheel on the page or only drag everything works fine, but then, If I wheel and then I drag, things break up and sometimes behave weirdly, but the main problem is that the coordinates of the borders on the drag gesture get shifted together with the wheel movement. I tried tracking this shift by introducing a state variable on the main scope of my component, then update that shift in coordinates everytime I use the wheel gesture, so that I can recalibrate my borders on the drag config everytime the wheel gesture kicks in, but that did absolutely nothing. Here's a sandbox:

https://codesandbox.io/s/use-gesture-test-i3n9o?file=/src/App.js

What am I missing and how would I implement this (scrolling or dragging - with rubberband ) to move the camera if not this way? That doesn't seem like a complex use case but I can't find any example on that anywhere. Please help! And thanks very much!</div>

**Comment by dbismut** [comment]
Is this an issue?

**Comment by danielx-art** [comment]
Seems buggy and inconsistent to me, with no solution or workaround, despite looking like a very common or simple problem that I don't find anyone talking about.

**Comment by dbismut** [comment]
If that's an issue, can you please describe the expected behavior, and suggest a minimal repro sandbox, possibly not including r3f?

**Comment by danielx-art** [comment]
I think one should expect the drag and wheel to be independent, and the drag bounds not to be influenced by the wheel gesture, but to be fixed in relation to the object's initial position, or maybe even, and that's a suggestion, it should be fixed in relation to another element. I don't think r3f should make it different, because it doesn't depend on the interaction with the canvas or anything, it is just a way of visualizing it.

**Comment by dbismut** [comment]
The drag bounds are not influenced by the wheel gesture. 

Even if it was the case, I'm pretty sure there would be a simpler way to express it than a sandbox using r3f. Dealing with your sandbox complexity is just increasing overload and makes it harder for me to understand what's happening and where the problem comes.

I'm closing this in favor of your question that you've linked as I can't frame an issue from your description. 

I'll reopen if answering your question reveals a clear bug.
