### ISSUE TITLE
Calling a setState function inside of useGesture can result in unexpected behavior

### ISSUE THREAD

**Issue by FaridHosman** [pmndrs/use-gesture#339]
**Describe the bug**
Calling a setState function inside of useGesture can result in unexpected behavior

**Sandbox or Video**
https://codesandbox.io/s/musing-lumiere-oxjo6?file=/src/App.js

In this example, as the user drags on the red square, dragCount goes from zero to 2 but rarely gets to 4, and then goes back to 2. Moving let count = 0 on line 7 somewhere outside of App() fixes the issue

**Information:**
 - React Use Gesture version: 9.1.3

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I'm not sure what you're trying to do here. `count` gets reassigned to `0` on every render and that's expected. Also setting state is not synchronous in React. 

Closing this as this seems like a React specific question rather than anything else, unless I'm missing something.

**Comment by FaridHosman** [comment]
You are right, it also happens onCLick. not a use-gesture issue. Sorry
