### ISSUE TITLE
useHover is not working with Cypress "mouseover / mouseenter" events

### ISSUE THREAD

**Issue by aldibatyr** [pmndrs/use-gesture#340]
**Describe the bug**
> After upgrading to version 9.1.3 Cypress tests fail due to not triggering `useHover` hook. Cypress tests break due to not finding elements that should be visible only on hover. 

**Sandbox or Video**
> 
![Screenshot from 2021-07-26 19-17-31](https://user-images.githubusercontent.com/47831819/126994892-520eac0e-c936-4d4d-a11f-f02ba6722026.png)

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: PC
 - OS: Fedora
 - Browser Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).
  - [N/A] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
This is a bug with Cypress rather than this lib no, isn't it?
