### ISSUE TITLE
`usePinch` attached to the parent element behaves like attached to each child element separately

### ISSUE THREAD

**Issue by WojciechKo** [pmndrs/use-gesture#344]
**Describe the bug**
I bound `usePinch` to the CSS grid container and it works only when both fingers are placed on the same grid item. When you place fingers on a separated items, the callback isn't fired.
Can you please help me with this? I have no idea anymore how to make it work for the whole parent element instead of for each child element separately.

**Sandbox or Video**
https://codesandbox.io/s/pinch-cra-87pgi

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: multiple
 - OS: Android
 - Browser Chrome

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Please upgrade to `@use-gesture/react` and report back. This bug is one of the many v10 solves.

**Comment by WojciechKo** [comment]
I've updated to `10.0.0-beta.22` and it works as expected.
I decided to use "stable" version because [documentation](https://v10-beta--use-gesture.netlify.app/) contains not working example and I assumed it's a deep beta.
Anyway, thanks for your quick reply and this library!

**Comment by dbismut** [comment]
I'm going to release v10 as stable soon now that I quitted my job and have some free time!
