### ISSUE TITLE
(Drag) Swiping characters not working on Android phones

### ISSUE THREAD

**Issue by justinLifelike** [pmndrs/use-gesture#345]
**Describe the bug**
Swiping between characters works like a charm on IOS but does not work at all on Android. 
I think that the problem could maybe be the fact that it detects a short swiping distance of less than 50. 
That's what I have seen in the console whenever the swiping is not working, but why would this only be on android or browser? 
So maybe the problem lies somewhere else? 

**Sandbox or Video**
> Cant show anything because I have signed a NDA 

**Information:**
 - React Use Gesture version: 9.1.3
 - Android not working
 - Browser {edge} only working sometimes 
 - Gsap : latest version 

**Checklist:**
  - [ v] I've read the [documentation](https://use-gesture.netlify.app/).
  - [v ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi, I can't and won't help if there's no repro sandbox, your NDA shouldn't prevent you from trying to reproduce a bug.
