### ISSUE TITLE
Rubberband position is calculated incorrectly with snap interval functionality

### ISSUE THREAD

**Issue by enheit** [pmndrs/use-gesture#346]
**Describe the bug**

I want to implement the list which can be dragged by a mouse and snapped to the closest row on mouse button release.

![closest-row-snap-interval](https://user-images.githubusercontent.com/8645216/132084148-8899f2ce-9ad3-40b5-bf2a-65c466727e57.png)

I use `useDrag` hook with `bounds` & `rubberband` properties as shown in the [documentation](https://v10-beta--use-gesture.netlify.app/docs/options/#rubberband).

Whenever I try to pull the list (to check the rubberband functionality) the position of the list seems to be calculated incorrectly. I want to emphasize that issue exist only when applying "snap" logic. If I remove this logic everything work as expected.

Also I was able to achieve the correct result by using [`rubberbandIfOutOfBounds` util](https://use-gesture.netlify.app/docs/utilities/#rubberbandifoutofbounds). It seems like issue exist somewhere within `rubberband` + `bounds` properties.

**Sandbox or Video**
Sandbox: https://codesandbox.io/s/beautiful-sound-pmfpw?file=/src/App.tsx

![Animation](https://user-images.githubusercontent.com/8645216/132084287-b4d7d61e-b4d4-4c28-903b-486d9121fd48.gif)

**Steps to reproduce**
1. Open sandbox
2. Slightly drag the `.draggable` element (like 2-5px) upward
3. Try to pull the list to trigger rubberband 
4. Release the mouse

Current result
The `.draggable` element "freezes" in the "middle" of the container

Expected result
The `.draggable` element should be pulled back to the initial position

**Information:**
 - React Use Gesture version: ^10.0.0-beta.23
 - Device: Desktop PC
 - OS: Windows 11
 - Browser Google Chrome. Version 93.0.4577.63 (Official Build) (64-bit)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi @enheit, I think I understand what you're trying to achieve, but the diagonal lines don't help understanding how the snap works.

Here's what I think should be a functional sandbox: https://codesandbox.io/s/sweet-andras-wmkbs
What you should be looking at is line 29 and the `from` attribute.

**Here's a short explanation:** the `bounds` property works out of the box when the dragged element position matches the `offset` vector from the gesture state. In your situation, you manually change the offset of the dragged element to make the snap work.

So eventually there will be a growing mismatch between the position of the dragged element and the `offset` vector from the gesture state on which bounds are calculated. Fortunately, the `from` option allows you to tell the lib that the gesture state `offset` should be based on an arbitrary vector, and generally it is used to reconcile the gesture state with the dragged element position, in your case `offsetY`.

 As a side note, I would advise using an animation library such as react-spring to avoid re-rendering the component on each event frame, and `initialOffsetY` should probably be used as a ref and not a state variable. Note that the gesture state conveniently exposes `state.lastOffset` which should completely remove the need for `initialOffsetY`. 

PS: also make sure to be using [v10 docs](https://v10-beta--use-gesture.netlify.app), they're mostly the same but there are some slight differences.

**Comment by enheit** [comment]
> ...but the diagonal lines don't help understanding how the snap works.

Agree, I had to use `0deg` with `50px` thickness to mimic the rows. But realized it after your answer. _(P.S. Without that background it almost impossible to notice that element is dragging on the gif animation)_

> ...As a side note, I would advise using an animation library such as react-spring to avoid re-rendering

Yes, I use `@react-spring/web` to work with animation. Also, I tried to store my offsetValue inside 
```typescript
const [{ offsetY }, api] = useSpring(() => ({ offsetY: 0 })
```
 and update it using `api.start({ offsetY: newOffsetY })` or `api.set(...)`. In my app I use this `offsetY` to calculate few more props for custom virtualization. Whenever I update the `offsetY` the value doesn't trigger component re-render and value become stale.

Let me show what I mean

```typescript
const FooComponent = () => {
  // Declare useSpring variable
  const [{ offsetY }, api] = useSpring(() => ({ offsetY: 0 })

  // Implement pseudo drag handler
  const bind = useDrag(state => {
     api.set({ offsetY: state.offset[1] }) // or api.start({ offsetY: state.offset[1], immediate: true })
  })

  // Try to see updates whenever offsetY changes
  console.log(offsetY.get()) // This console.log will not be printed on drag and startIndex value will not be re-calculated respectively.
 

  // Calculate startIndex depending on the `offsetY` value
  const startIndex = Math.ceil(offsetY.get() / 50) // where 50 is a item height

   return (
     <div {...bind()} ... />
   )
}
```

That's why I introduced a new value which mimic spring value to be able to trigger component updates to calculate `startIndex` for my needs.

I tried to google this problem and some ppl proposed to use it inside `useEffect` but unf it didn't help.

Any ideas?

**Comment by dbismut** [comment]
You could either use a ref or compute a state variable in the gesture handler at the end of the gesture (when `state.last` is `true`).

**Comment by enheit** [comment]
@dbismut I applied `from` prop as you suggested in [your codesandbox example](https://codesandbox.io/s/sweet-andras-wmkbs). Rubberband works as expected with my snap functionality. Thank you.

I close this issue due that fact that I closed it on my side.

Thank you a lot
