### ISSUE TITLE
Drag gesture breaks hover gesture

### ISSUE THREAD

**Issue by smashercosmo** [pmndrs/use-gesture#348]
**Describe the bug**
When drag gesture is specified, it breaks hover gesture. Any click on an item makes item non-hovered.

**Sandbox or Video**
https://codesandbox.io/s/use-gesture-bug-mgq2g

**How to reproduce**
1. Open codesandbox
2. Hover over green square
3. See that square becomes red
4. Now click on the square
5. See that square becomes green again

**Information:**
 - React Use Gesture version: 10.0.0-beta.23

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by smashercosmo** [comment]
without onDrag handler everything works correctly

**Comment by dbismut** [comment]
Looks like this is a r3f bug rather. Looks like adding pointer capture triggers pointer leave. Here's a demo reproducing the bug without use-gesture. Can you file this on r3f repo?

**Comment by smashercosmo** [comment]
Alright, will do
