### ISSUE TITLE
I would like to extend the documentation of the velocity prop

### ISSUE THREAD

**Issue by enheit** [pmndrs/use-gesture#350]
I didn't find how to open PR for the documentation and decided to open this issue here.

I was looking for the description of how the `velocity` prop is calculated and what this value means (`1.2`, `0.5`, `-0.2` etc). After a while, I was able to find in the source code that this value is actually px / ms. Would be nice to have it inside documentation like this.

Before

```javascript
const bind = useXXXX(state => {
  const {
    ...
    velocity,      // momentum of the gesture per axis
    ...
  } = state
})
```

After

```javascript
const bind = useXXXX(state => {
  const {
    ...
    velocity,      // momentum of the gesture per axis (px / ms)
    ...
  } = state
})
```

What do you think?

**Comment by dbismut** [comment]
Hey, look at the upcoming change in v10 regarding velocity: https://github.com/pmndrs/use-gesture/blob/v10/.changeset/swift-carrots-shout.md

In other words the velocity momentum you're describing in v9 is gone (it wasn't very useful in real life scenarios). 

I'll close the issue but we can continue discussing this here.

**Comment by enheit** [comment]
@dbismut yes, I am already using the latest version of `use-gesture`. Is my proposal not valid for the v10? It seems like the values still px / ms? Am I wrong?

**Comment by dbismut** [comment]
Oh right sorry. I'll add that then (although it wouldn't be pixels when using the `transform` option).

**Comment by dbismut** [comment]
Done :)
