### ISSUE TITLE
Browse Docs button on main page of docs site not working

### ISSUE THREAD

**Issue by david-buck** [pmndrs/use-gesture#356]
**Describe the bug**
> A clear and concise description of what the bug is.

Browse Docs button on the main page of docs site not working

**Sandbox or Video**
> If applicable, please provide a minimal reproduction sandbox on code sandbox. Or a video / screenshots that could help.

https://raw.githubusercontent.com/pmndrs/use-gesture/main/documentation/pages/index.mdx

```
<Button variant="primary" forwardedAs={Link} to="/docs/" style={{WebkitAppearance: 'none'}}>
   Browse Docs
</Button>
```

ends up as 

```
<button type="button" data-variant="primary" as="[object Object]" to="/docs/" class="sc-bqGGPW Button__InnerButton-sc-1qxez5q-0 bUceVa iGzYAt" style="appearance: none;">Browse Docs</button>
```

In the output code

**Information:**
MacOS 10.14.7
Chrome 94

**Comment by dbismut** [comment]
Thanks! Should be fixed now!
