### ISSUE TITLE
UseDrag action-sheet example not working for v10

### ISSUE THREAD

**Issue by david-buck** [pmndrs/use-gesture#357]
Supplied example in use-gesture docs

![image](https://user-images.githubusercontent.com/5119820/134982311-c189b6b9-7dfe-49a4-83a0-ab57fc32a71f.png)

https://codesandbox.io/s/github/pmndrs/use-gesture/tree/v10/demo/src/sandboxes/action-sheet

When dragging throws this error:

TypeError
Cannot destructure property 'Symbol(Symbol.iterator)' of 'undefined' as it is undefined.

```
  22 | const bind = useDrag(
> 23 |   ({ last, vxvy: [, vy], movement: [, my], cancel, canceled }) => {
```

![image](https://user-images.githubusercontent.com/5119820/134982032-9ab0b1c9-f84c-4798-b0a1-418210b83886.png)

The issue also occurs when running locally

![image](https://user-images.githubusercontent.com/5119820/134982233-f1dd5906-0946-40b5-ab4f-ea44971212bb.png)

**Information:**
 - React Use Gesture version 10
 - OS: MacOS 10.14.6
 - Browser Chrome 94

**Comment by dbismut** [comment]
Indeed, thanks for pointing this out, `vxvy` is removed in v10 in favor of `velocity` which is now a vector. I've updated the repo, should be fixed now.
