### ISSUE TITLE
"API" link in docs nav missing trailing slash

### ISSUE THREAD

**Issue by david-buck** [pmndrs/use-gesture#358]
Sorry, this is another tiny one

![image](https://user-images.githubusercontent.com/5119820/135198911-ad2e5e22-50de-4d77-8ea5-0a4f8c4f2763.png)

The API link in the docs header is missing a trailing slash so when it's clicked, the sidebar navigation doesn't show as active

![image](https://user-images.githubusercontent.com/5119820/135198972-7c38945d-ee3e-4d1d-b295-739a915b0f24.png)

Can be fixed on line 20 of https://github.com/pmndrs/use-gesture/blob/main/documentation/gatsby-config.js

```
        navItems: [
          { title: 'Docs', url: '/docs/' },
          { title: 'API', url: '/docs/gestures/' }
        ],
```

**Comment by dbismut** [comment]
Wow nice catch! Thanks for reviewing the doc site btw. If there's anything you'd want to improve please submit ideas / PR. Writing docs is not my strongest suit, so if there's anything you'd think would be better phrased or explained let me know!

**Comment by david-buck** [comment]
The docs are really good. I'm not a strong developer, but I managed to track down a solution to an issue by reading the docs. 

If I find any more things, I'll join them together in a PR.
