### ISSUE TITLE
Typescript: this expression is not callable.   Type 'void' has no call signatures

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/use-gesture#362]
**Describe the bug**
This expression is not callable.
  Type 'void' has no call signatures
![msedge_2021-10-06_00-39-45](https://user-images.githubusercontent.com/300961/136074764-5f866ec0-0858-41dd-9c45-cc2dbf54b0c7.png)

**Sandbox or Video**
The official demo has this bug too: https://codesandbox.io/s/github/pmndrs/use-gesture/tree/v10/demo/src/sandboxes/draggable-list?file=/src/App.tsx

**Information:**
 - React Use Gesture version: 10
 - Typescript ^4.3.2
**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Thanks for reporting this, but it's not a bug in the lib :)

Here's the linting in a properly configured project:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/5003380/136088794-4c0e8be9-5680-413c-9ddb-5d6f40525bc6.png">

I've just add `tsconfig.json` files to all typescript sandboxes and now it works fine: the official example link is actually: https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/draggable-list?file=/src/App.tsx

You probably copied an outdated link from the beta v10 documentation, that I just corrected (so thanks!).

**Comment by alvinalexander** [comment]
I am having the same error using typescript 4.3.5. Looking at the type definition for `useDrag` I see 

```ts
export declare function useDrag<EventType = EventTypes['drag'], Config extends UserDragConfig = UserDragConfig>(handler: Handler<'drag', EventType>, config?: Config | {}): Config["target"] extends object ? void : (...args: any[]) => import("@use-gesture/core/types").ReactDOMAttributes;

```
Even though `Config['target']` is not defined in my code, the typescript compiler still treats the return value from useDrag as `void`. My workaround was to assigna a ref to the `target` attribute and omit the use of `{...bind()}` completely

**Comment by dbismut** [comment]
@alvinalexander Please provide a sandbox. As seen above this was a documentation error. In any case changing code logic because of type potential error is never a good idea.

**Comment by Blackhardd** [comment]
...
"moduleResolution": "node"
...
In tsconfig.json causes this error. No idea how to fix this at this time.
https://codesandbox.io/s/intelligent-christian-9kwye?file=/src/App.tsx

**Comment by Blackhardd** [comment]
Looks like
`"strictNullChecks": false`
in tsconfig.json may cause this error.

**Comment by dbismut** [comment]
@Blackhardd I'm not sure why this would cause an error.
@alvinalexander There's some tests in the lib for types, and that use case should be covered here.

https://github.com/pmndrs/use-gesture/blob/72e579d0698e619b2464d51c1559efd1cbba9cfa/packages/react/src/types.test.ts#L20

The lib is now up to date with TypeScript `4.5.2`, maybe upgrading your TS version could help.

However, the sandbox here https://codesandbox.io/s/runtime-monad-c5h78?file=/src/App.tsx doesn't trigger an error with TS set to `4.3.5`.

Please provide a sandbox showing the bug and I'll be happy to have a look. Discussing an issue without tangible examples is not productive in this case.

**Comment by Blackhardd** [comment]
> 

![image](https://user-images.githubusercontent.com/6304775/144393100-aa0b15df-3ba7-4c53-b15d-011640b80557.png)
https://codesandbox.io/s/intelligent-christian-9kwye?file=/src/App.tsx

**Comment by dbismut** [comment]
Hm ok actually you're right about `"strictNullChecks": false`, didn't know `undefined` and `null` would be completely ignored, but now reading the docs that make sense. Well, this isn't something I can fix as far as I know.

**Comment by meotimdihia** [comment]
In my case, I have tried to upgrade to TypeScript `4.5.2` and it solved the problem.

**Comment by alvinalexander** [comment]
@dbismut It's a little hard to provide a sandbox because the error only occurs at build time when I run `tsc -b` locally. I don't get an error from the vscode language server during development. I could provide more context about my local setup if that is helpful. In short, I am running node `v16.12.0` with typescript `4.3.5`.  I am working in a monorepo managed by nrwl.   I don't have `strictNullChecks: false` in my compiler options.

**Comment by alvinalexander** [comment]
I will try upgrading TS

**Comment by CKGrafico** [comment]
+1 any fix?

**Comment by dbismut** [comment]
@CKGrafico this issue is closed because I can't identify it, so I'm not even working on it. You're welcome to submit a sandbox highlighting a problem.

**Comment by Blunderchips** [comment]
Still seems to be failing

**Comment by Blunderchips** [comment]
Code snippet take from the README

```tsx
function Example() {
  const [{ x, y }, api] = useSpring(() => ({ x: 0, y: 0 }))

  // Set the drag hook and define component movement based on gesture data.
  const bind = useDrag(({ down, movement: [mx, my] }) => {
    api.start({ x: down ? mx : 0, y: down ? my : 0 })
  })

  // Bind it to a component.
  //@ts-ignore
  return <animated.div {...bind()} style={{ x, y, touchAction: 'none' }} />
}
```

![image](https://user-images.githubusercontent.com/7081037/148268575-b40d48ed-6177-4324-b108-819be2270405.png)

**Comment by dbismut** [comment]
@Blunderchips there seems to be unrelated errors in your screenshot. Please submit a sandbox on codesandbox showing the issue and I'll consider discussing this further.

**Comment by do-kevin** [comment]
Setting `strictNullChecks: true` in my tsconfig.json fixed it for me.

**Comment by teamchong** [comment]
one quick fix is add a ! to the assignment of the bind variable to indicate it is not void

instead of 
const bind = useScroll(........)

do this
const bind = useScroll(........)!

**Comment by smalljiaot** [comment]
the other option is to do const bind:any = useDrag(); that way you dont have to mess with tsconfig.

**Comment by callumacrae** [comment]
For anyone looking for a workaround that retains type safety and doesn't change any config:

```ts
import type { ReactDOMAttributes } from '@use-gesture/react/dist/declarations/src/types';
```

then…

```ts
  const bind = useDrag(fn) as unknown as (...args: any[]) => ReactDOMAttributes;
```

This is the same type as declared in the use-gesture types - but be careful when updating. I'm on @use-gesture/react@10.2.22.
