### ISSUE TITLE
Diagonal or custom axis constraint?

### ISSUE THREAD

**Issue by jackwlee01** [pmndrs/use-gesture#377]
Is it possible to define a custom axis at a given angle? I have a requirement to constrain movement along a 30 degree axis, but it appears the available constraints are only for the x and y axis?

**Comment by dbismut** [comment]
This is a relatively exotic request, I don't think it would make sense to implement it in the lib. 

Just to clarify: do you just want the dragged element to follow a 30deg slope, or do you want the drag gesture (ie the cursor) to start with a 30deg slope?

**Comment by jackwlee01** [comment]
No worries, I thought that may be the case.

I want the dragged element to follow a 30deg slope.

**Comment by dbismut** [comment]
In that case it should be fairly easy to implement this in your handler. 

What the `axis` option does is more than just nullifying the other axis movement, it actually doesn't trigger the drag at all if the initial movement is on the other axis.

That means that if you start the movement on the other axis than the one you've specified, even the axis you have movement logic for will remain null until you restart the drag in the correct direction. 

Hope this helps clarifying as why a custom angle for `axis` would be hard to implement and doesn't make much sense to implement on the lib's side. 

I'll close this but if someone else has the same request I can always reconsider!

**Comment by jackwlee01** [comment]
Thanks, I'll look into implementing it in my handler.
