### ISSUE TITLE
Threshold config not working for wheel on the latest version

### ISSUE THREAD

**Issue by NachoVazquez** [pmndrs/use-gesture#379]
**Describe the bug**

Moving from v9 to v10 makes the threshold for the wheel gesture to start working.

**Sandbox or Video**

https://codesandbox.io/s/lethargy-forked-uxcg9?file=/src/index.js

Follow the Instruction in the import section.

**Information:**
 - React Use Gesture version: ^10.0.0
 - Device: [Macbook Pro]
 - OS: [Catalina]
 - Browser [Chrome 95]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hmm the example doesn't use `threshold`, is that expected?

**Comment by NachoVazquez** [comment]
This modified version has it, I only used the example because it was already set up.

But it happens without lethargy too (which is the extra piece here).

Thanks for taking a look.

**Comment by dbismut** [comment]
@NachoVazquez should be fixed in latest release! Thanks for letting me know, rookie mistake.

**Comment by NachoVazquez** [comment]
Awesome thanks for taking care so quickly!
