### ISSUE TITLE
Feature Request: richer pointer.buttons API

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/use-gesture#385]
mysterybear — 02/11/2021
https://use-gesture.netlify.app/docs/options/#pointerbuttons I want to be able to listen to left clicks and right-clicks, but I seem to only be able to use this to stipulate a necessary combination (like an AND combination, rather than an OR one)

dbismut — 03/11/2021
@mysterybear indeed not feasible out of the box
Either we make an option like pointer.buttons: -1 which would make the drag triggered for every combination
Or we make buttons accept an array (probably cleaner)

mysterybear — Today at 18:13
Yeah, why not both? -1 for just give me everything, array for granular OR-like control, bitmask for granular AND-like control?

Cheers @dbismut, thanks for all your hard work :love_hotel:

**Comment by dbismut** [comment]
@mysterybear just submitted PR #386 that should address all this. Have a look at the linked sandbox and let me know if this works out for you.

https://codesandbox.io/s/optimistic-maxwell-l1yr3

**Comment by mysterybear** [comment]
looks good to me @dbismut :+1:

**Comment by mysterybear** [comment]
Sorry my bad, if I add 3 to the options (which should require left and right click together) it doesn't work

**Comment by dbismut** [comment]
@mysterybear I don't have an external mouse to test this, and there's no specific logic in the lib that handles combinations, it only relies on `event.buttons`. I've added you on Discord so we can chat about this.

**Comment by mysterybear** [comment]
@dbismut I've tested and it makes sense. The reason it doesn't work is because the buttons specified in the pointer options are the buttons for initiating the drag movement, and it's impossible(?) to initiate a gesture with a combination of buttons because you can't actually press each button at precisely the same time (one will always be pressed before another) therefore the event that triggers the gesture, the first event, will always pertain to only a single button and not a combination... Therefore the bitmasking/AND combination aspect of this, so far as use-gesture is concerned, is irrelevant

If anyone did want to code logic to deal with the AND kind of button combinations, they'd want to allow the keys of the combination in the OR way (i.e. `pointer: { buttons: [1,2] }`) and then write the code to check `event.buttons` in the handler for movement, understanding that the `first` event (and likely some others, though also never the `last` I think) won't have the buttons combination

So I think the PR is all good and working! Cheers @dbismut !
