### ISSUE TITLE
Pointer touch set to true is no longer calling drag handler

### ISSUE THREAD

**Issue by jzombie** [pmndrs/use-gesture#392]
**Describe the bug**
pointer.touch: true no longer working on mobile

**Sandbox or Video**
https://codesandbox.io/s/dawn-wood-ovi8f?file=/src/App.js
Test link:  https://ovi8f.csb.app/

In the test, if you touch the top box on mobile, it won't execute the drag handler.  The bottom box proceeds just fine.  I've ensured touch-action is set to none on the draggable element, as shown in the code sandbox.

![demo](https://user-images.githubusercontent.com/1139657/141719933-3574e1cd-0ba2-429b-a8f3-fad16f90930e.png)

**Information:**
Tested on various versions of iOS simulator and Android

**Checklist:**
  - [x ] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by jzombie** [comment]
This was originally working in my codebase, and stopped working after rebuilding package-lock.json from scratch.  Updated to latest @user-gesture/react and still experiencing issue.

**Comment by awmleer** [comment]
Seems like it is related to this line of code:
https://github.com/pmndrs/use-gesture/blob/ec3b80a398d9e240d8ed91faf99fd1790c1ef4e8/packages/core/src/engines/DragEngine.ts#L87

I encountered the same issue and after I manually set `pointer.buttons` to `-1`, it works.

**Comment by dbismut** [comment]
Sorry about this, I'll release a fix today.

**Comment by awmleer** [comment]
@dbismut I've submitted a pull request. I tested on my project and it looks ok. Please take a look at it. Thanks a lot! This bug is due to the operation priority.

**Comment by jzombie** [comment]
Hi @awmleer thanks for the patch.

I revisited what I was working with and was able to get it to work with the pointer events correctly, but if I wind up in the dilemma I was in before, I'll keep this in mind.
