### ISSUE TITLE
useDrag swipe triggers in the wrong direction for certain devices

### ISSUE THREAD

**Issue by uelibaumgartner** [pmndrs/use-gesture#409]
**Describe the bug**
Two quick swipes in a row trigger the wrong swipe direction (possible due to a weird interaction with react spring). 

We encounter this bug only with Firefox and only for a specific device type. But there it's so bad it basically makes our app unusable. To better understand this issue I stripped down everything to the bare essentials: [https://omkth.csb.app/](https://omkth.csb.app/)

**Video**
![Video Link](https://user-images.githubusercontent.com/38912007/145119601-fa798bc1-191f-4ac8-8001-95a96adb35b1.mp4)

**Code**
[https://codesandbox.io/s/omkth](https://codesandbox.io/s/omkth)

**Information:**
 - React Use Gesture version: [@use-gesture/react@^10.2.2]
 - React Spring version (if this is any help): [@react-spring/web@^9.3.1]
 - Device: [Galaxy S20 5G SM-G981B/DS]
 - OS: [Android 11]
 - Browser [Firefox Browser 94.1.2]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hi, please make a sandbox so I can have a proper look. Thanks.

**Comment by uelibaumgartner** [comment]
So I created the codesandbox - Hope this helps.

I understand that it probably isn't feasible to try to fix this if you can't reproduce it. Anyways, if you have some suspicion on what it could be I can offer my assistance by checking it for you.

Then something a bit off-topic: On chrome mobile onClick events (e.g. on the heart) are not registered right after swiping. I was planning to raise another question/issue but if you take a look at it anyways: Is this to be expected or is it a bug?

**Comment by TPME** [comment]
Hi @dbismut , I am having the same issue as documented here. Any chance you could please look into this?

**Comment by dbismut** [comment]
@TPME what hardware / browser please?

**Comment by TPME** [comment]
@dbismut Sorry, I was specifically talking about the issue that the onClick event is not registered right after swiping. I end up having to tap twice (instead of just once). I can also re-create the bug in the code sandbox @uelibaumgartner linked in the original post now.

I am using a Samsung S20 with Chrome Browser (latest).

**Comment by dbismut** [comment]
@TPME Oh right ok. Sorry I've let this issue stall a bit. I don't have an android device around unfortunately so I can't reproduce on my iPhone (Firefox, Safari, Chrome seem to work properly).

**Comment by uelibaumgartner** [comment]
@dbismut I just good feedback, that this is very likely an issue tied to this specific device of this user. Therefore I'll close this issue.

For the other think where onClick events are not triggered that @TPME also is affected, I will raise a separate issue and with a better codesandbox, that really highlights the issue.

**Comment by dbismut** [comment]
Thanks! Sorry I let this one stalled, just got a new job that takes me away from OSS.
