### ISSUE TITLE
Pinch and wheel mutually exclusive ?

### ISSUE THREAD

**Issue by odusseys** [pmndrs/use-gesture#419]
**Describe the bug**

I am trying to handle both pinch and wheel gestures. However using the code below, only one of the handlers is able to fire (wheel, in this case). Note that I have tried putting "target" only on the shared config object or only on the individual configs - same result.
Is this on purpose ? I couldn't find anything pointing towards it in the docs.

```
 useGesture(
    {
      onPinch: (e) => {
        console.log(e.offset[0]);
      },
      onWheel: (e) => {
        console.log(e);
      },
    },
    {
      target: ref,
      pinch: {
        target: ref,
        preventDefault: true,
      },
      wheel: {
        target: ref,
        preventDefault: true,
      },
    }
```

**Information:**
 - React Use Gesture version: 10.2.4
 - Device: Mac
 - OS: Monterey
 - Browser: Chrome

**Comment by dbismut** [comment]
Hi, are you able to provide a sandbox? Thanks.

**Comment by dbismut** [comment]
https://codesandbox.io/s/upbeat-hermann-zr1m3?file=/src/App.jsx:791-910

This seems to be working as intended.
