### ISSUE TITLE
don't work onDragEnd event in mobile browser for gesture

### ISSUE THREAD

**Issue by PROCW** [pmndrs/use-gesture#423]
**Describe the bug**
> In mobile browser, onDragStart Event worked, but onDragEnd Event doesn't work with gesture.
I added my source.

```
import { useSpring, a } from '@react-spring/three';
import { useGesture } from 'react-use-gesture';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useLoader } from "@react-three/fiber";

import useMachineStore from "../../store";

export const Knob = () => {
    const model = useLoader(GLTFLoader, './model/Knob.glb');

    const updateCanRotate = useMachineStore(state => state.updateCanRotate);

    const [spring, set] = useSpring(() => ({ 
        scale: [ 0.4, 0.4, 0.4 ], 
        rotation: [0, 0, 0], 
        position: [-2.5, -1.1, 1.2],
    }));

    const bind = useGesture({
        onDragStart: () => {
            updateCanRotate(false);
        },
        onDrag: ({ offset: [x, y], delta: [dx, dy]}) => {
            set({ rotation: [0, 0, -x / 5] });

            const wrapper = document.getElementsByClassName('cardImages')[0];
            if( wrapper )
                wrapper.scrollTop = wrapper.scrollTop;
        },
        onDragEnd: () => {
            updateCanRotate(true);
        }
     })

    return (
        <a.group {...spring as any} {...bind()}>
            <group rotation={[0, Math.PI, 0]} >
                <primitive object={ model.scene } receiveShadow />
            </group>
        </a.group>
    )
}

export default Knob;

```
[duck-machine.vercel.app](https://duck-machine.vercel.app/) in mobile web browser.
OnDragEnd should be called when the Knob button is rotated and the mouse button is released, but it is not called.
But this is worked in pc browser.

**Information:**
 - React Use Gesture version: [10.2.4]
 - Device: [iPhoneX]
 - Browser [Chrome browser]

**Comment by dbismut** [comment]
Please provide a sandbox.

**Comment by dbismut** [comment]
I'm asking for a minimal repro sandbox. Building it on your end reduces my time fixing the bug by 90%, also because you might figure out the bug isn't in the lib itself.

**Comment by PROCW** [comment]
Sorry, if you give me email, I can invite in github.

**Comment by dbismut** [comment]
@PROCW Here's a sandbox taken from the example using `onDragEnd`. Performs as expected.
https://codesandbox.io/s/agitated-firefly-zikvb?file=/src/App.tsx
