### ISSUE TITLE
Bounds do not seem to be respected if target is larger than bounds

### ISSUE THREAD

**Issue by odusseys** [pmndrs/use-gesture#431]
**Describe the bug**
Consider the following situation:
- a large canvas contained in a smaller viewport
- we attach a wheel gesture to the viewport with bounds which are smaller than the canvas
- the gesture state is incorrect: the offset is correct but the distance however is not subject to bounds
- this results in having to scroll the viewport in the opposite direction several times before being able to start navigating the viewport again (the distance is reduced, but the offset remains constant during the gestures)

**Sandbox or Video**
https://codesandbox.io/s/dazzling-cookies-webhj?file=/src/App.js

**Information:**
 - React Use Gesture version: latest
 - Device: Macbook Pro
 - OS: 12.0.1
 - Browser: chrome

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Is this what you're trying to achieve? https://codesandbox.io/s/sad-microservice-gdhum?file=/src/App.js

**Comment by odusseys** [comment]
yes sorry - but actually if you pay attention to what happens in your sandbox, here's what happens
- try dragging quickly towards the left
- immediately after stopping, drag towards the right
you will see that the square will remain immobile for a moment before starting to drag again
However, if you pause for a second after finishing the first gesture and drag the other way, it will start moving immediately.

I think I have figured out what is happening: since the canvas is larger (try making it even larger to see the effect more strongly), the drag event has large inertia and keeps firing for a while after the touch is released - the offset is kept inbounds but the new gesture is not registered as long as the previous is happening. This causes the object to remain static while the first gesture inertia ends (which is unexpected)

**Comment by dbismut** [comment]
Inertia is a classic problem when working with wheel, that's why libs like [Lethargy](https://github.com/d4nyll/lethargy) exist. I can see if there's anything I can do about this.

**Comment by odusseys** [comment]
just saw in the doc right before you answered hehe, I'm trying it out to see if I can cancel the gesture as soon as it goes to inertia and my bounds are reached - but I think this should be done by the lib

**Comment by odusseys** [comment]
Also using lethargy, I don't see any way of stopping the gesture - state.event.preventDefault() (passive set to false) does nothing and the gesture keeps going

**Comment by odusseys** [comment]
Found the bug 

In packages/core/src/engines/CoordinatesEngine.ts

![image](https://user-images.githubusercontent.com/7863870/150996076-6f40d03d-7e5d-4fff-b352-d788edc5a901.png)

Here, you compute the offset based on the last offset (which is clamped to bounds) and the movement, which is not. Therefore, when the inertia has passed the bounds, you need to scroll a lot more to make the offset catch up. I think you need to clamp the movement to bounds as well.

**Comment by dbismut** [comment]
@odusseys `offset` is clamped further in the logic.

First `offset` is calculated as if it wasn't clamped.

https://github.com/pmndrs/use-gesture/blob/1b9cd356198093c5544593609a05666dc2370c6b/packages/core/src/engines/Engine.ts#L301

Then `offset` is clamped.

https://github.com/pmndrs/use-gesture/blob/1b9cd356198093c5544593609a05666dc2370c6b/packages/core/src/engines/Engine.ts#L320-L321

And finally `movement` is calculated based on the `offset`.
As said previously, I believe this is specific to how wheel behaves.

**Comment by dbismut** [comment]
Thinking about this further: I get your point.
The logic that I mentioned above is generic to all gestures. Indeed, the offset to catchup but that makes sense on a drag let's say.

Let's say you drag an element until it's blocked by the bounds to its left, and then you continue dragging further left with your mouse (off the bounds). The element will catch up only when your mouse is back within the bounds (and that's the accepted behavior). Otherwise the element would start moving as soon as you'd start dragging back to the right.

For wheel I admit this is a bit different since there's no reference to where your wheel position actually is. So it would make sense to **not track** the offset when it gets off the bounds, so that wheeling back would update its position immediately.
