### ISSUE TITLE
onPinch delta value is state sensitive

### ISSUE THREAD

**Issue by softmarshmallow** [pmndrs/use-gesture#435]
the pinch delta value is not consistent by its movement.

https://user-images.githubusercontent.com/16307013/151671332-563ef25d-db53-44f1-a0a5-d82263602ec6.mov

What you are seeing is that sacling delta being messed up by the time passes.
at one point, the delta gets very small, that you can't see the scaling.

repo: 
- https://github.com/gridaco/designto-code
- https://github.com/gridaco/designto-code/blob/staging/editor-packages/editor-canvas/canvas-event-target/canvas-event-target.tsx

**Comment by dbismut** [comment]
How exactly am I suppose to debug this? Please edit your issue following the issue's template and I'll reopen.

**Comment by dbismut** [comment]
Just to clarify: I'm not going to debug your app. Please provide a MINIMAL repro sandbox.

**Comment by mauricedoepke** [comment]
I experience the same issue on an ipad. I was implementing a zoom function like this:

```tsx
  const mapElemForGestures = useRef<HTMLDivElement>(null)
  useGesture({
    onPinch: ({ delta: [dZoom], intentional }) => {
      if (!intentional) return;
      setZoom(zoom + dZoom);
    }
  }, {
    target: mapElemForGestures,
  })
```

Initially the dzoom value is big enough to change the zoom meaningfully. But after using the function a bit, at some point randomly it becomes very small.
