### ISSUE TITLE
Docs search is broken

### ISSUE THREAD

**Issue by goleary** [pmndrs/use-gesture#437]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16123225/152069719-955f1389-0263-4dd9-b353-e3da2f4ace78.png)

This error shows up in the console:
```
{name: 'ApiError', message: 'Invalid Application-ID or API key', status: 403, transporterStackTrace: Array(1)}
message: "Invalid Application-ID or API key"
name: "ApiError"
status: 403
```

**Information:**
 - OS: Windows 11
 - Browser: Chrome

**Comment by dbismut** [comment]
Thanks for raising this. I had to upgrade the documentation packages which took some time!
