### ISSUE TITLE
useDrag with `pointer: { touch: true }` stucks on iOS after pulling the home bar

### ISSUE THREAD

**Issue by awmleer** [pmndrs/use-gesture#441]
**Describe the bug**

Open the codesandbox below on iOS devices. When you drag the gray box, it follows. Then, hold the gray box with one finger, and pull the iOS home bar up with another finger **at the same time**. And then, release the two fingers. Now, the gray box get stuck. No matter how you drag it, it won't move or trigger the callback of `useDrag`.

If you comment line 17, which is `pointer: { touch: true }`. This bug will not exist. So maybe this is related to touch events.

I've search the issues of use-gesture, seems this bug is somehow like #349. But I think they are two different bugs.

**Sandbox or Video**

Sandbox:

https://codesandbox.io/s/use-gesture-stucks-when-switching-between-apps-on-ios-fdsxl?file=/src/App.js

Video with the sandbox above:

https://user-images.githubusercontent.com/16526078/152717896-d28fcda0-29c3-43fb-a3bd-4aad62c8c9ee.MP4

Another video with a real picker component:

https://user-images.githubusercontent.com/16526078/152718245-969569b1-18b1-4482-bfa0-6f7d8545a0d9.MP4

**Information:**
 - React Use Gesture version: 10.2.5
 - Device: iPhone 12 mini
 - OS: iOS 15.2.1
 - Browser: Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Hey @awmleer thanks for the detailed issue. This should be fixed in [10.2.6](https://www.npmjs.com/package/@use-gesture/react/v/10.2.6)!

**Comment by awmleer** [comment]
Great! It works now!
