### ISSUE TITLE
Documentation - Redeclaration of `const` 

### ISSUE THREAD

**Issue by spencerkordecki** [pmndrs/use-gesture#445]
**Describe the bug**
Within the documentation at the link below, there's a few examples that use a pattern like this:

```
// This will work as intended
function DragAndPointerDown() {
  const [{ x, y }, api] = useSpring(() => ({ x: 0, y: 0 }))
  const bind = useGesture({
    onDrag: ({ down, offset: [x, y] }) => api.start({ x, y }),
    onPointerDown: ({ event, ...sharedState }) => console.log('pointer down', event)
  })
  return <animated.div {...bind()} style={{ x, y }} />
}
```

The problem is that if someone copy/pastes this example, ESLint throws an error because the `x` and `y` variables used on line 2 and 4 of the example collide with each other. While a user could certainly just disable ESLint for that line, it's also of note that the example could be changed to avoid any kind of redeclaration by changing the variables to something like `springX`, or just not destructuring on line 2 and putting into a `coordinates` object (or something of the sort) that would get spread on the div instead of referencing just `x`, `y`. 

I know this is just an example in the documentation so copy/pasting isn't always the best idea for these things, but it could help with newcomers to the library to remove that one extra step of renaming/disabling ESLint.

**Information:**
https://use-gesture.netlify.app/docs/gestures/#native-event-handlers-in-react

**Comment by dbismut** [comment]
This is your lint rule that prevents naming conflicts in variables even though they're not in the same scope.
