### ISSUE TITLE
UseDrag do not work in ios 12.5

### ISSUE THREAD

**Issue by menaka123** [pmndrs/use-gesture#448]
**Describe the bug**
> I have use the ios simulator to test my current app in the Ios 12.5 ipad air but UseDrag do not seems to work properly init, I open the samples in it and they response in the same way  

**Sandbox or Video**
>  Check this example in a ios 12.5 simulator => https://h4vgh.csb.app/

**Information:**
 - React Use Gesture version: 9.1.3
 - Device: ios simulator (ipad air)
 - OS: ios 12.5
 - Browser safari

**Comment by dbismut** [comment]
Please update the lib to its latest version, earlier versions aren't supported. Also don't expect anyone to test something in a simulator running a 3 year old OS. Thanks.
