### ISSUE TITLE
confirm delay option default value...

### ISSUE THREAD

**Issue by Rabbitzzc** [pmndrs/use-gesture#449]
**Describe the bug**
> file: https://github.com/pmndrs/use-gesture/blob/main/documentation/pages/docs/options.mdx
```ts
<Specs gestures={['drag']} types={['boolean', 'number']} defaultValue="0" />
```
the `defaultValue` should be '180ms'.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/26913511/154439737-4031495f-beb4-4967-8037-69a8499db390.png">

**Comment by dbismut** [comment]
`180ms` is the default value when delay is `true`. But by default delay is set to `0ms`.
