### ISSUE TITLE
Hard to explain, handlers on different components looks like they deny the final drag with down: false

### ISSUE THREAD

**Issue by lucax88x** [pmndrs/use-gesture#458]
**Describe the bug**
I'll probably try to create a sandbox, but It'll require some time, in the meantime I wanted to post a quick video about the "problem".

You can see I have a "tabs" component in the screen, that I can drag on the x axis, and as soon as I leave my finger ({down: false}) I try to put the tab to the correct position, and this works flawlessly.

The problem is that when I open this "menu" from the right, which is a useDrag bound to the window and using { capture: true, passive: false } in order to block propagation then the useDrag of the "tabs" stops sending the final event (the one with {down: false}) and I cannot place my tabs back to their position.

**Sandbox or Video**

https://user-images.githubusercontent.com/6294464/156811468-d31073b7-64fc-4368-a4c8-a202346dc001.mp4

**Information:**
 - React Use Gesture version: 10.2.7
 - Device: PC 
 - OS: Archlinux
 - Browser Chrome 99

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Have a look at this sandbox: https://codesandbox.io/s/use-gesture-template-forked-ygn4tz
The yellow rect acts as some sort of handle for the menu to the right. I've left it yellow so you can actually see it, but you can have it transparent if you want.

Let me know what you think, whether it matches the usecase.
