### ISSUE TITLE
OnPinch update scale error

### ISSUE THREAD

**Issue by Nicolerobinn** [pmndrs/use-gesture#467]
**Describe the bug**
> When I scale with onPinch, I update the value of scale externally via api.start of useSpring, and then I scale again using onPinch instantly changes from the value I set in api.start to the value I set before。For example, if I set the value before API. Start to {scale: 0.2}, then I set the value to {scale: 0.2}. 1}, and then I use onPinch again, and the scale changes from 1 to 0.2 in an instant, the element changes from 1 to 0.2

**Sandbox or Video**
> 

**Information:**
 - React Use Gesture version: [ v7.0.2]
Google Chrome 101.0.4919.0
**Checklist:**
  I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by dbismut** [comment]
Closing until you actually follow the issue template.
