### ISSUE TITLE
Unable to get ralative coordinates of an element.

### ISSUE THREAD

**Issue by herbievine** [pmndrs/use-gesture#471]
**Describe the bug**
I was trying to recreate the card effect as displayed [here](https://codesandbox.io/s/vigilant-tdd-w3ngdw), but noticed, that if you want the element to actually be used in a website, you don't have access to its x and y position (I created an example of what I mean [here](https://codesandbox.io/s/sleepy-saha-nudz2v)). I found a workaround using the `onMouseLeave` and `onMouseMove` events, but would be nice if you could integrate it into the `useMove` function.

**Sandbox or Video**
[My take on it](https://codesandbox.io/s/cold-breeze-yuf4fq)

**Information:**
 - React Use Gesture version: latest

**Comment by dbismut** [comment]
You're not using the latest version of use-gesture.

**Comment by herbievine** [comment]
Well, could you show me how to do it then? I've tried for hours and asked on SO... Thanks
