### ISSUE TITLE
touch-action on iOS Safari

### ISSUE THREAD

**Issue by ukrutt** [pmndrs/use-gesture#486]
**Describe the bug**
On iOS 15.4.1, Safari browser, the `touch-action` behaviour suggested in https://use-gesture.netlify.app/docs/extras/#touch-action does not work well. If I try to drag the boxes horizontally, I need to slide *perfectly horizontally* -- if not, the drag stop and the screen scrolls instead.  NOTE: it works very well with the Chrome browser on iOS!

A workaround/solution to this is to set `preventScroll: true` (https://use-gesture.netlify.app/docs/options/#preventscroll) -- I'm reporting this more as a documentation issue.  (Also, `preventScroll` is advertised as an experimental feature.)

**Sandbox or Video**
https://user-images.githubusercontent.com/1161208/164729457-b6acd4a4-eb89-4064-9c2c-e7b5f43dbd2d.MOV

**Information:**
 - Use Gesture version: Whatever's currently on your web site
 - Device: iPhone 12 -- this has also been seen 
 - OS: iOS 15.4.1
 - Browser: Stock/Safari.  (Chrome does not have this problem)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I've noticed that for a while and this is just infuriating. Chrome works ok but for some reason pan-y stopped working properly in Safari. This is absurd. In those situations I'm now looking at methods similar to https://kor-ui.com/components/swipe-actions involving overflow.

**Comment by dbismut** [comment]
You can also use `preventScroll: true` as a config option in `useDrag`.
