### ISSUE TITLE
Open a new page will lock the scroll of the old page

### ISSUE THREAD

**Issue by awmleer** [pmndrs/use-gesture#494]
**Describe the bug**

Open the codesandbox below. The web page should be able to scroll normally. Then click on one of the cards. It'll open a new page. Switch back to the sandbox page and you'll find the whole page can't be scrolled.

Seems like the scroll lock doesn't get released… Also I found this bug only occurs when `preventScroll` is set to `true` and in `@use-gesture/react` v10.2.13.

I think this bug was introduced by 6896094b, which solves #485.

**Sandbox or Video**

For preview: https://1b8n4s.csb.app/
With editor: https://codesandbox.io/s/late-sound-1b8n4s?file=/src/App.js

https://user-images.githubusercontent.com/16526078/168585768-23ea3ba3-eae3-46c3-b828-81440f00b8fe.MP4

**Information:**
 - Use Gesture version: 10.2.13
 - Device: iPhone 12 mini
 - OS: iOS 15.4.1
 - Browser iOS Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Indeed. This is must be due to this commit: https://github.com/pmndrs/use-gesture/commit/6896094b312da0efadbdad15e81f4fc0f8dc0b26#diff-bdb226cd6a706170fbb3438b6eefc36f52e23458ac4190aace4c5d11c89d3a11, I knew this would fire back somehow.

**Comment by awmleer** [comment]
v10.2.14 works now. Thanks!
