### ISSUE TITLE
After clicking the slide, the first drag event get ignored

### ISSUE THREAD

**Issue by awmleer** [pmndrs/use-gesture#497]
**Describe the bug**

Open the codesandbox below on **iOS Safari**. Drag the slides and they should work properly. Then click (tap) on the slide. And then, try to drag it. You'll find the first dragging get ignored. You need to drag twice to flip the slide.

Besides, v10.2.12 does not have this bug. So this seems to be related with #494 and #485. 😅

**Sandbox or Video**

https://codesandbox.io/s/fast-mountain-8z02ig?file=/src/App.tsx

**Information:**
 - Use Gesture version: v10.2.14
 - Device: iPhone 12 mini
 - OS: iOS 15.4.1
 - Browser: iOS Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I'm beginning to die inside 😅
I've spotted the issue and understand where it comes from, not sure how I'm going to solve this though.

**Comment by dbismut** [comment]
Took less than I thought, should be fixed in next release @awmleer.
