### ISSUE TITLE
Typescript: Type incompatibility error when using Gesture with the vanilla package

### ISSUE THREAD

**Issue by SteveoKr** [pmndrs/use-gesture#507]
**Describe the bug**
When using the vanilla package in combination with Typescript, the `Gesture` class shows a type incompatibility error for the handlers.

After looking a bit through the underlying type definitions I noticed that the `Target` type in `packages/core/src/types/utils.ts` depends on `React.RefObject` even though the core package does not have a dependency on React types. This results in `Target` to resolve to `any` instead and causes the original error.

```ts
// packages/core/src/types/utils.ts:
export type Target = EventTarget | React.RefObject<EventTarget>
```

As a workaround additionally installing `@types/react` solves the issue.

**Sandbox**
https://codesandbox.io/s/nifty-diffie-8mfxcw?file=/src/index.ts:0-114
```ts
import { Gesture } from "@use-gesture/vanilla";

new Gesture(
  window,
  {
    onDrag: (state) => { /* ... */ }
  },
  {}
);
```

**Information:**
 - Use Gesture version: v10.2.15

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by dbismut** [comment]
Ah yeah I see, thanks for the heads up. Ref objects are ultimately `{ current: any }` so I guess I can just cast it without using React. Will release a fix asap.

**Comment by dbismut** [comment]
Hey @SteveoKr would you mind testing https://github.com/pmndrs/use-gesture/pull/508 if this solves the issue on your end?

**Comment by SteveoKr** [comment]
Thanks for the quick fix! I tested it and there was still an issue with the onDrag handler. I added the corresponding suggestion to #508.

**Comment by dbismut** [comment]
Hey @SteveoKr the new version is now out. Let me know if it works out for you!
