### ISSUE TITLE
Can't zoom in or out in iframe

### ISSUE THREAD

**Issue by ty888** [pmndrs/use-gesture#516]
**Describe the bug**
> Can't zoom in or out in iframe

**Sandbox or Video**
https://codesandbox.io/s/an-niu-lei-xing-antd-4-21-6-forked-t7h1wx?file=/demo.js
**Information:**
 - Use Gesture version: [e.g. v10.2.10]

**Checklist:**
  - [ ] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I won't be able to help without a sandbox.

**Comment by dbismut** [comment]
Can you please tick the two checkboxes from the issue template? As it seems you haven't set touch-action anywhere.

**Comment by ty888** [comment]
@dbismut help

**Comment by dbismut** [comment]
So the bug occurs on your laptop?

**Comment by ty888** [comment]
> So the bug occurs on your laptop?
yes, happens in my project

**Comment by ty888** [comment]
> So the bug occurs on your laptop?

yes, happens in my project

**Comment by ty888** [comment]
@dbismut I've tried using pointerEvents: "none" on the iframe, but that blocks me all.

**Comment by dbismut** [comment]
It's touch-action

**Comment by ty888** [comment]
> It's touch-action

So there is no solution for this problem on laptops

**Comment by dbismut** [comment]
This lib doesn't do much magic. It doesn't interfere with events.

This shows a working sandbox with iFrame zoom and container zoom both working.
https://codesandbox.io/s/cant-zoom-in-or-out-in-iframe-516-forked-xi0ogo
