### ISSUE TITLE
Animations stuttering on Firefox when dragging elements

### ISSUE THREAD

**Issue by benslv** [pmndrs/use-gesture#528]
**Describe the bug**
Animated elements (using `@react-spring/web`) move in a stuttery/low-framerate motion when dragged in Firefox. This same motion is absolutely fine when using Google Chrome.

I checked to see if this was an issue with `@react-spring/web` but upon switching out the `@use-gesture/react` package with (the now deprecated) `react-use-gesture` the stuttery behaviour disappears and elements move smoothly.

**Sandbox or Video**
>[Sandbox link](https://codesandbox.io/s/spring-vs-native-and-immediate-forked-kl3qsp?file=/src/App.js)

Replacing the `@use-gesture/react` with `react-use-gesture` on Line 3, you should be able to see the problem resolve itself.

**Information:**
 - Use Gesture version: 10.2.17
 - Device: Windows PC
 - OS: Windows 10 21H2
 - Browser: Firefox 103.0.1 (64-bit)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
I'm currently on my phone, but in both cases (new use-gesture and old react-use-gesture) react-spring with `immediate: true` seems to stutter when animating with style directly is smooth.

There could be a bug in the lib so take this with a bit of salt but it doesn't do heavy math and just basically fires events when they come. So there's no reason why use-gesture would cause a lag here.

**Comment by benslv** [comment]
Interesting, okay. I suppose I could maybe "crosspost" this issue over on the react-spring repo and see what they think about it. I don't want to spam too much and, honestly, I'd love to be able to fix it myself but I think it's very much out of my depth.

**Comment by dbismut** [comment]
I had already reported this to the react-spring team (either Discord, DM or GitHub), this is exactly what I had set up this sandbox in the first place. I'm going to analyze this a bit more later on.

**Comment by dbismut** [comment]
@benslv I'm on my Mac now. I've updated everything to its latest package, and also added my animation lib (far from stable) into the mix. I'm using Firefox and I'm not seing any difference between the old / new use-gesture package, no matter the animation lib being used. Lmk your feelings, and feel free to close if this looks like a non-issue.
