### ISSUE TITLE
Missing types in useWheel hook

### ISSUE THREAD

**Issue by michelecocuccio** [pmndrs/use-gesture#529]
Hello! Thanks for the awesome library!

I have noticed that the properties `last` and `memo` are not typed correctly in the `useWheel` hook. I have followed the example provided to[ use wheel with Lethargy ](https://codesandbox.io/s/lethargy-2coe8?file=/src/index.js) but when this is used with Typescript it throws an error as the properties `last` and `memo` that are contained in the `SharedGestureState` are omitted I guess.

`Property 'last' does not exist on type 'Omit<SharedGestureState & CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { event: WheelEvent; }, "event"> & { ...; }'ts(2339)`
`Property 'memo' does not exist on type 'Omit<SharedGestureState & CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { event: WheelEvent; }, "event"> & { ...; }'.ts(2339)`

![Screenshot 2022-08-10 at 17 24 23](https://user-images.githubusercontent.com/8071249/183949571-b9133aea-b9d3-4299-a0aa-4f3088302ba4.png)
![Screenshot 2022-08-10 at 17 24 38](https://user-images.githubusercontent.com/8071249/183949587-16f0a11f-422b-44f3-b9fc-6e3a7b55697d.png)

**Information:**
 - Use Gesture version: 10.2.17

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Thanks for raising an issue. Can you please send a repro sandbox as asked in the issue template? Thanks

**Comment by dbismut** [comment]
There are other closed issues about a similar problem. It's likely to be your local typescript config. 

https://github.com/pmndrs/use-gesture/issues/501

I'll reopen if you're able to submit a repro sandbox on Codesandbox.
