### ISSUE TITLE
typebug, useScroll has no xy parameters

### ISSUE THREAD

**Issue by datner** [pmndrs/use-gesture#537]
**Describe the bug**
pretty straightforward, the types got broken once I upgraded my typescript from 4.7 to 4.8

**Sandbox or Video**
<img width="707" alt="image" src="https://user-images.githubusercontent.com/22598347/187673567-8f0715e2-c975-44a7-b4e7-b070af616317.png">

**Information:**
 - Use Gesture version: v10.2.11 through v10.2.19 tested
 - Device: Macbook pro 
 - OS: idk latest, doesn't really matter for this bug
 - Browser: ts-server 🤨

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by datner** [comment]
I technically can send you the repo, but it's quite big and I am not sure it'll be productive, but the tsconfig is pretty easy to send

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "baseUrl": "./",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "noUncheckedIndexedAccess": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "tsBuildInfoFile": ".tsbuildinfo"
  },
  "exclude": ["node_modules", "**/*.e2e.ts", "cypress"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

**Comment by datner** [comment]
for whats its worth, `typescript` published a new minor like 4 hours ago. Which might have re-broke it? 🤔

**Comment by dbismut** [comment]
@datner here's a small repo. Just run yarn install and yarn tsc. I'm not getting any errors on my end so I'll close until further notice..
 
[nyw1ln.zip](https://github.com/pmndrs/use-gesture/files/9491496/nyw1ln.zip)
