### ISSUE TITLE
onDrag + onClick with threshold and filterTaps does not work as expected

### ISSUE THREAD

**Issue by kriskolve** [pmndrs/use-gesture#552]
**Describe the bug**
When using onDrag and onClick handlers together inside useGesture it is desirable to isolate drag Events from Click events. It should be possible to do this with threshold:<some number> and filterTaps:true so that:
1) when clicking (without moving the mouse) only the onClick event fires.
2) When Dragging only the dragging associated events fire, no onClick at the end.

_Actual Behavior_:
Individually threshold and filterTaps properties work as expected. 
However, when used together, items behave as if only filterTaps is set, so that when clicking with out moving onDrag Event is fired along with onClick. 

**Sandbox or Video**
`export interface Props extends PropsWithChildren {

}

const BoardSVG = (props:Props) => {

  const svgRef = useRef(null)

  useGesture({
    onWheel:(state)=>{
      // state.event.stopPropagation()

      console.log("svg onWheel", state)
    },
    
    onDrag:(state)=>{
      // state.event.stopPropagation()
      console.log("svg onDrag", state)
    },
    onClick:(state)=>{console.log("svg onClick", state)},
    
  }, {
    target:svgRef,
    eventOptions:{passive:false, capture:true},
    drag:{
      threshold:10, // Alone will prevent onDrag from firing when clicking; however on Click fires at end of Drag
      filterTaps:true, // Alone will prevent onClick from firing at end of drag; However, onDrag will fire, when clicking.
      //When both are active filterTaps does not seem to do anything.
    },
    // wheel:{}
  })

  return(
    <svg
      ref={svgRef}      
      style={{
        width:'100%', height:'100%', touchAction:'none'
      }}
    >
      {props.children}
    </svg>
  )
  
}

export default BoardSVG`

**Information:**
 - Use Gesture version: 10.2.21
 - Device: MacBook Pro
 - OS: 12.6 (21G115)
 - Browser: Chrome 106.0.5249.119

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Please provide a proper sandbox
