### ISSUE TITLE
Got "Type 'undefined' is not assignable to type 'DragBounds'"  inside bounds config of useDrag function

### ISSUE THREAD

**Issue by barconvizit** [pmndrs/use-gesture#555]
**Describe the bug**
Hi, I'm getting a typescript compiling error for the callback parameter when the bounds attribute of the config object is defined as a callback.
For some reason the type is inferred as a union of several types including undefind which is the cause of the problem.

The full detailed error:
```
TS2322: Type '(event: (CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { _pointerId?: number | undefined; _pointerActive: boolean; _keyboardActive: boolean; ... 5 more ...; swipe: Vector2; } & { ...; }) | undefined) => { ...; } | ... 2 more ... | undefined' is not assignable to type 'DragBounds | ((state: (CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { _pointerId?: number | undefined; _pointerActive: boolean; ... 6 more ...; swipe: Vector2; } & { ...; }) | undefined) => DragBounds) | undefined'.   Type '(event: (CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { _pointerId?: number | undefined; _pointerActive: boolean; _keyboardActive: boolean; ... 5 more ...; swipe: Vector2; } & { ...; }) | undefined) => { ...; } | ... 2 more ... | undefined' is not assignable to type '(state: (CommonGestureState & { axis: "x" | "y" | undefined; xy: Vector2; } & { _pointerId?: number | undefined; _pointerActive: boolean; _keyboardActive: boolean; ... 5 more ...; swipe: Vector2; } & { ...; }) | undefined) => DragBounds'.     Type '{ right: number; bottom?: undefined; } | { right: number; bottom: number; } | { bottom: number; right?: undefined; } | undefined' is not assignable to type 'DragBounds'.       Type 'undefined' is not assignable to type 'DragBounds'.
```
<img width="419" alt="image" src="https://user-images.githubusercontent.com/109509955/201681123-e9353eb6-9e7f-4e22-8802-ef8364b2a935.png">

Here is my tsconfig:
```
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "noImplicitAny": true
  },
  "include": [
    "src"
  ]
}
```

**Information:**
 - Use Gesture version: [v10.2.22]
 - Device: [Desktop PC]
 - OS: [Windows 11]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
@barconvizit not able to reproduce. Please test this sandbox locally and tell me if you see the same error.
https://codesandbox.io/s/strange-leaf-rfj1fs?file=/tsconfig.json

If the sandbox doesn't seem right to you, please fork it and send it back to me.

**Comment by dbismut** [comment]
Sure don't hesitate to post what was wrong so it might be helpful for others ;)

**Comment by barconvizit** [comment]
I had some logic which didn't return a value so the actually inferred return value type was a union with undefined :/
