### ISSUE TITLE
Examples (on codesandbox) are broken.

### ISSUE THREAD

**Issue by thomasf1** [pmndrs/use-gesture#565]
**Describe the bug**
The examples (e.g. https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/viewpager) display a 
TypeError
Cannot convert undefined or null to object

I´ve tried different browsers, pretty sure that shouldn´t happen.

**Comment by dbismut** [comment]
I'll check this but AFAIK CSB uses an old version of typescript no matter your dev deps.
