### ISSUE TITLE
The examples were broken

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/use-gesture#572]
**Describe the bug**
The example doesn't work 
```js
[@use-gesture]: You've created a custom handler that that uses the `drag` gesture but isn't properly configured.

Please add `dragAction` when creating your handler. 
    in App 
```
https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/viewpager
https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/card-zoom

**Information:**
 - Use Gesture version: 
 - Device: iPhone/Mac
 - OS: iOS/MacOS
 - Browser Chrome/Safari

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
This is related to https://github.com/pmndrs/use-gesture/pull/560 and on CSB side. You can try to download the sandbox locally and check that it works. I know it's a bummer but there's not much I can do beside downgrading the package.

**Comment by dbismut** [comment]
This is related to https://github.com/pmndrs/use-gesture/pull/560 and on CSB side. You can try to download the sandbox locally and check that it works. I know it's a bummer but there's not much I can do beside downgrading the package.

**Comment by dbismut** [comment]
Sandboxes should be working now, CSB has fixed the bug
