### ISSUE TITLE
TypeError in Example

### ISSUE THREAD

**Issue by bidinzky** [pmndrs/use-gesture#579]
The Examples:
* [draggable-list](https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/cards-stack?file=/src/App.tsx)
* [cards-stack](https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/cards-stack)
* [viewpager](https://codesandbox.io/s/github/pmndrs/use-gesture/tree/main/demo/src/sandboxes/viewpager)

cant be used because of an TypeError.

Its always cannot convert undefined or null to object in useDrag

**Comment by dbismut** [comment]
This is already commented. It's an error from Codesandbox I can't fix this on my own. Rolling back to 10.2.22 or downloading this locally solves this issue.

**Comment by dbismut** [comment]
Sandboxes should be working now, CSB has fixed the bug
