### ISSUE TITLE
useDrag is noticeably less responsive than useMove using Firefox

### ISSUE THREAD

**Issue by HeartofPhos** [pmndrs/use-gesture#581]
**Describe the bug**
Dragging a div using `useDrag` appears to stutter compared to `useMove`, this happens while using Firefox but not Edge.
The issue is not noticeable at 60hz, a high refresh rate display is required to reproduce the issue, it is easily noticeable at 120hz/240hz

The issue occurs regardless of whether react-spring spring being used.

**Sandbox or Video**
[Sandbox](https://stackblitz.com/edit/react-ts-fpesmf?file=package.json,App.tsx) (updated)
[Video](https://user-images.githubusercontent.com/43216176/216820630-516c9505-be61-431b-a9ef-abdf1314c3f4.mp4)

**Information:**
 - Use Gesture version: 10.2.24
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox 109.0.1 (64-bit)

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Unfortunately I only have a 60hz monitor at the moment.
But the useMove code is broken, you should either setPointerCapture or attach events to the window.

**Comment by HeartofPhos** [comment]
Indeed, the sandbox was broken, I've updated it, I've also added a video recorded at 120hz but slowed down by 50% so that the difference is visible at 60hz

**Comment by dbismut** [comment]
Hi @HeartofPhos, finally had the time to look into this.
Can you try the following sandbox?

https://stackblitz.com/edit/react-ts-wmbqww?file=App.tsx

I've removed react-spring to focus on the lib only. The red square uses the genuine `useDrag` from the library while the green square uses a simplified implementation of `useDrag`.

**Comment by HeartofPhos** [comment]
> Hi @HeartofPhos, finally had the time to look into this. Can you try the following sandbox?
> 
> https://stackblitz.com/edit/react-ts-wmbqww?file=App.tsx
> 
> I've removed react-spring to focus on the lib only. The red square uses the genuine `useDrag` from the library while the green square uses a simplified implementation of `useDrag`.

This issue seems to still be present, the red square still has significant stuttering while the green square is smooth as expected

**Comment by HeartofPhos** [comment]
I've rerecorded the issue at 240fps and slowed the footage to 0.25 speed.

https://user-images.githubusercontent.com/43216176/236677895-f445d53d-9efd-4770-a32f-19fb745133b4.mp4

**Comment by dbismut** [comment]
Thanks. There's a few things we could try but I'm afraid we'll have to try a debug session together as I'm not sure I'll be able to reproduce the issue on my own, not having a 120hz monitor. Can you try adding me on discord?

**Comment by dbismut** [comment]
For reference and following our call @HeartofPhos, we've observed that the issue comes from this line:
https://github.com/pmndrs/use-gesture/blob/4dcbf8c601281f726d8176a20e27e314a3941e64/packages/core/src/engines/DragEngine.ts#L155

In fact, [because of Firefox protection against fingerprinting](https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp#reduced_time_precision), the `event.timeStamp` precision is reduced which, on high framerate monitors result in successive events to be skipped.

 The options would be:

1. don't calculate kinematics for events with a similar timestamp
2. use `performance.now()` rather than `event.timeStamp` (but this may have a performance cost).
