### ISSUE TITLE
Using pointer.touch cannot be dragged under windows system

### ISSUE THREAD

**Issue by JarvisArt** [pmndrs/use-gesture#583]
**Describe the bug**
> Using pointer.touch cannot be dragged under windows system. It can be used normally on mac system

**Sandbox or Video**
> https://codesandbox.io/s/stoic-paper-t11ikx?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/38420763/220026659-0cee5411-c2f0-4bc9-8226-9e6e06afa802.png)

**Information:**
 - Use Gesture version: [v10.2.24]
 - Device: [Any windows computer]
 - OS: [windows10]
 - Browser [google chrome]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Thanks for the report. 

Any windows computer, are you sure?

Also, can you try copy pasting those lines in the console?

```
'ontouchstart' in window

window.navigator.maxTouchPoints > 1)

'onpointerdown' in window


'exitPointerLock' in window.document
```

**Comment by JarvisArt** [comment]
> Any windows computer, are you sure?

Yes, many of our windows users have had feedback that they can't drag, and I couldn't even try it myself

windows10
<img width="265" alt="企业微信截图_16768753598235" src="https://user-images.githubusercontent.com/38420763/220032285-b31c64f0-642a-4cce-ab68-8fe3f711603d.png">

**Comment by JarvisArt** [comment]
Mac
![image](https://user-images.githubusercontent.com/38420763/220032546-6a11a85d-6c10-4e96-9cfe-764620d5966c.png)

**Comment by dbismut** [comment]
Is it working without touch:true?

As essentially the lib SHOULD fall back to pointer events considering the windows 10 capture, even when touch:true is set.

**Comment by JarvisArt** [comment]
> Any windows computer, are you sure? 

I want to correct that this is a problem with Lenovo Thinkpads
https://github.com/airbnb/is-touch-device/issues/2

**Comment by JarvisArt** [comment]
> As essentially the lib SHOULD fall back to pointer events considering the windows 10 capture, even when touch:true is set.

can you help me quickly ❤️

**Comment by dbismut** [comment]
I'm on holidays so depends on what you mean by quickly. Also I won't be able to help without someone having access to the device. What time zone are you on?

**Comment by JarvisArt** [comment]
I am in China.

**Comment by dbismut** [comment]
Closed because of inactivity
