### ISSUE TITLE
node16 moduleResolution resolves to CJS build instead of ESM

### ISSUE THREAD

**Issue by cseas** [pmndrs/use-gesture#584]
**Describe the bug**

@use-gesture packages ship with a dual package build. The expectation is that an ESM project should resolve to the ESM build shipped by the package. But it is resolving to the CJS build.

<img width="293" alt="Screenshot 2023-02-27 at 10 29 03 AM" src="https://user-images.githubusercontent.com/29686866/221478338-dfd75fa3-ef6c-48c9-aec0-bb57437d16d2.png">

<img width="293" alt="Screenshot 2023-02-27 at 10 31 36 AM" src="https://user-images.githubusercontent.com/29686866/221478372-d9ffc93c-e7b2-4ef6-8c11-511729940935.png">

Possible fix can be to either add a `package.json` with `"type": "module"` to the esm build directory. Or rename the esm build files to `.mjs` file extension.

**Sandbox or Video**

Refer: https://arethetypeswrong.github.io/

**Information:**
 - Use Gesture version: v10.2.24
 - Device: NA
 - OS: NA
 - Browser: NA

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by Andarist** [comment]
> The expectation is that an ESM project should resolve to the ESM build shipped by the package. But it is resolving to the CJS build.

Why this is an expectation? :) If you are loading this through node you will end up with a CJS build. You can still require/import it. When you bundle things then most of the modern bundlers should pick up the file defined by the `module` **condition** and that is written in ESM.

**Comment by cseas** [comment]
I got a bit confused by the output of https://arethetypeswrong.github.io/
Opened https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/9 for clarity.

I just saw that the package only has one types file `use-gesture-core.cjs.d.ts` that is used even for ESM imports. Got confused by the `cjs` part in the filename, but looks like it is working as intended.
