### ISSUE TITLE
Wrong event mentioned in documentation

### ISSUE THREAD

**Issue by AdrianFahrbach** [pmndrs/use-gesture#609]
**Describe the bug**
On the introduction page under [How does this work?](https://use-gesture.netlify.app/docs/#how-does-this-work) it says that bind will add `onMouseDown` even though it actually is `onPointerDown` as mentioned [here](https://use-gesture.netlify.app/docs/gestures/#native-event-handlers-in-react).
I guess this was changed some time and not adjusted which is a bit confusing when you specifically want to disable on of those events by overwriting it.

**Comment by dbismut** [comment]
Thanks for pointing this up. Fixed.
