### ISSUE TITLE
Drag event is interrupted when dragged element is removed.

### ISSUE THREAD

**Issue by xianjie-li** [pmndrs/use-gesture#611]
**Describe the bug**

If a drag is started from container element's child element and that child element is removed during the drag, the event will only be triggered within the container element.

**Sandbox or Video**

https://codesandbox.io/s/new-silence-68drvx?file=/src/index.js

**Information:**
 - Use Gesture version: [v10.2.27]
 - Device: [Macbook]
 - Browser [chrome 114]

**Comment by dbismut** [comment]
@xianjie-li I think this is intrinsically linked to how `setPointerCapture` works which is the default behavior of the lib. If you still want this to work, you can add `{ pointer: {capture: false} }` as a parameter so that events are attached to the window.
