### ISSUE TITLE
Not usable in NextJs Typescript after building

### ISSUE THREAD

**Issue by ktjh123** [pmndrs/use-gesture#616]
Works as expected when running next dev but after building and running next start, it dosent work at all. 

    "@use-gesture/react": "10.2.27",
    "next": "13.4.12",
    "react": "18.2.0",
    "react-dom": "18.2.0",

Typescript project

**Comment by BenCoDev** [comment]
I have the same issue

**Comment by dbismut** [comment]
I won't look at this until it follows the proper issue template.

**Comment by BenCoDev** [comment]
Yep, sure. I test a few things and come back by tmr!

**Comment by BenCoDev** [comment]
Created this issue: https://github.com/pmndrs/use-gesture/issues/618#issue-1859155914
Tell me if there are any info missing, thanks a lot for looking at it ✨
