### ISSUE TITLE
useGesture hook is not called once deployed on Vercel

### ISSUE THREAD

**Issue by BenCoDev** [pmndrs/use-gesture#618]
**Describe the bug**
`useGesture` is not called once deployed on Vercel, though it works on localhost.
Note: using the `useMove` hook works on Vercel.

**Sandbox or Video**
https://www.loom.com/share/58023fd24d834f70b1b66ca11ba9fa53?sid=90b505e4-20a5-4bcf-85af-501ac3a318d2

**Information:**
 - Use Gesture version: [v10.2.27]
 - Device: [MacBook Pro 2021]
 - OS: [Ventura 13.3.1]
 - Browser [Arc 1.4.0]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Thanks for this. I'll have a look asap. This is using React right?

**Comment by BenCoDev** [comment]
Using react with next.js yes

**Comment by kobeaerts** [comment]
For us, the issue happens when using the "old" pages directory.
You're example is using the new "app" directory, sadly we're not able to update our app to the new "app" directory.

**Comment by BenCoDev** [comment]
> This is a sandbox using NextJS https://codesandbox.io/s/cocky-resonance-tc73nf Deployed on Vercel: https://csb-tc73nf-ny1cri7fk-dbismut.vercel.app
> 
> Works as it should. I might be wrong but I guess you're being confused with server / client components.

I use the App router, with "use client" set on at the top of the file containing the component using `useGesture`. So, I think it is clear about where the component is rendered.



> For us, the issue happens when using the "old" pages directory. You're example is using the new "app" directory, sadly we're not able to update our app to the new "app" directory.

Ok thanks, to be clear, do you mean that `useGesture` is not tested on the new app router?

**Comment by dbismut** [comment]
The sandbox I've submitted is using Next JS app router.

I'm not sure why I should "test" the lib with Next JS specifically, it's just a front-end lib with using client-side browser APIs.

If there's an issue, please provide a non working sandbox.

**Comment by dbismut** [comment]
> For us, the issue happens when using the "old" pages directory.
> 
> You're example is using the new "app" directory, sadly we're not able to update our app to the new "app" directory.

Can you please provide a repro repo / sandbox?

**Comment by kobeaerts** [comment]
Hey @dbismut there are no issues with the useMove / usePinch / use... hooks.
The only one that "fails" is the combined useGestures hook hope this helps!

**Comment by kobeaerts** [comment]
Hey @dbismut there are no issues with the useMove / usePinch / use... hooks.
The only one that "fails" is the combined useGestures hook hope this helps!

**Comment by dbismut** [comment]
@kobeaerts I've just redeployed my sandbox and used `useGesture` and it works. There's nothing I can do until someone provides me a dysfunctional repro. Closing until then.

**Comment by diginikkari** [comment]
@kobeaerts @BenCoDev Were either of you able to figure out what was the issue? I'm having the same issue with next.js production build and trying to figure out what is affecting this.
