### ISSUE TITLE
Using pointer.touch cannot be dragged under windows system

### ISSUE THREAD

**Issue by joannazhu88** [pmndrs/use-gesture#626]
**Describe the bug**
> Using pointer.touch cannot be dragged under windows system. It can be used normally on mac system
> I encountered the same problem like this issue: https://github.com/pmndrs/use-gesture/issues/583

**Sandbox or Video**
> If applicable, please provide a minimal reproduction sandbox on code sandbox. Or a video / screenshots that could help.

``
import React from 'react';
import { useSpring, animated } from '@react-spring/web';
import { useDrag } from '@use-gesture/react';

export default function Test() {
  const [{ x, y }, api] = useSpring(() => ({ x: 0, y: 0 }));

  const bind = useDrag(
    ({ down, movement: [mx, my] }) => {
      console.log('drag work---->');
      api.start({ x: down ? mx : 0, y: down ? my : 0, immediate: down });
    },
    { pointer: { touch: true } },
  );
  return (
    <>
      <animated.div {...bind()} style={{ x, y, boxShadow: 'rgba(0, 0, 0, 0.15) 0px 1px 2px 0px' }}>
        box
      </animated.div>
    </>
  );
}
``

**Information:**
 - Use Gesture version: [v10.2.27]
 - Device: [ windows computer]
 - OS: [window 10]
 - Browser [google chrome]

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by joannazhu88** [comment]
This function always return true in window 10 system
![image](https://github.com/pmndrs/use-gesture/assets/144769743/7e28d207-86e0-4727-a72a-fa19ed5effcf)

![image](https://github.com/pmndrs/use-gesture/assets/144769743/edd0d740-adb6-4b29-be71-e8635b20eb71)

**Comment by dbismut** [comment]
Hm interesting... that kind of sucks. I'll see what I can do but I don't have much time atm.

**Comment by joannazhu88** [comment]
Can you  filter msMaxTouchPoints === 10 in window 10? 
It is not a touch screen.
The ua is  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'.
![image](https://github.com/pmndrs/use-gesture/assets/144769743/eeda390a-a0e8-4baa-ad00-6c0719af7d39)
Is this information helpful？
msMaxTouchPoints is read-only,I can not modify.

**Comment by dbismut** [comment]
I'd like to avoid relying on user agent.

**Comment by dbismut** [comment]
Should be fixed in `10.3.0`, can you try once again?

**Comment by joannazhu88** [comment]
Thank you very much! I  will try.
