### ISSUE TITLE
DragBounds ignored when rerender target

### ISSUE THREAD

**Issue by FearZee** [pmndrs/use-gesture#632]
**Describe the bug**
> If the target is positioned at the edge of the bounds and the width or height is changed with a rerender, the bounds are ignored until the target is dragged again.

**Sandbox or Video**
> Sandobx(https://codesandbox.io/s/amazing-lena-cr8jzt?file=/src/App.tsx:765-771)
![useGesture](https://github.com/pmndrs/use-gesture/assets/38909210/26e03385-f69b-4585-83c3-71fa63b421a3)

**Information:**
 - Use Gesture version: v10.2.25
 - Device: Windows / Mac
 - OS: Win11 / MacOs 13.5.1
 - Browser: Chrome, Firefox

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
Yes bounds are calculated when the drag is initiated. It would trigger to many repaints otherwise.
