### ISSUE TITLE
dynamically updating useDrags axis option resets movement : [mx,my] 

### ISSUE THREAD

**Issue by damiaanh** [pmndrs/use-gesture#634]
**Describe the bug**
I try to create a draggable component that locks on the x OR the y axis based on the users drag intention. 
This works fine when dragging in one direction, but whenever the dragAxis is set to undefined and then "lock" again, the movements [mx, my] is reset to 0,0 multiple times. Resulting in a glitchy UI.  For me it is important to lock and release an axis, while in one drag movement. 

What I want to create is an effect like this:
https://github.com/pmndrs/use-gesture/assets/32978132/8375d8ff-0f11-4955-96e1-caef256e3c6d

Maybe my approach is wrong to get to the above behaviour. If so, please let me know (the [classic xy problem ](https://xyproblem.info/):)). Also, let me know if I need to provide additional information.

**Sandbox or Video**
My behaviour:
https://codesandbox.io/s/usedrag-axis-example-8yqjwm?file=/src/App.js

**Information:**
 - Use Gesture version: 10.3.0
 - Device: mobile and Framework laptop
 - OS: Android and Linux
 - Browser: Firefox

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).
  - [X] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by jur-ng** [comment]
I was able to partially work around your problem by storing the axis in a ref instead of a React stateful variable: https://codesandbox.io/s/usedrag-axis-example-forked-pqkmcg?file=/src/App.js
It is now possible to move diagonally as well, however I think this is a problem with the way you detect the direction instead of with the library itself.

**Comment by damiaanh** [comment]
Using a ref gives me indeed the behaviour I want. Thank you!

**Comment by damiaanh** [comment]
@jur-ng this works for me, thanks.
