### ISSUE TITLE
Drag + Click + filtertaps option breaks onclick listener. Drag + Click + Treshold works.

### ISSUE THREAD

**Issue by LeunensMichiel** [pmndrs/use-gesture#638]
**Describe the bug**
I have this moveable div. It has a drag and click listener (dragging moves the div, clicking selects it). When dragging an element (and you let go), the click handler does not get called when you click it afterwards and having options `filtertaps: true` and `preventDefault: true`. If I change `filterTaps: true` to `treshold: 3` (which is a default parameter IIRC), the clickhandler becomes responsive again after dragging it.

**Sandbox or Video**
/

**Information:**
 - Use Gesture version: [v10.3.0]
 - Device: M1 Pro Macbook (touchpad)
 - OS: Macos 14
 - Browser: Chrome 119 and Safari 17

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**Comment by dbismut** [comment]
The sandbox / video is not optional.
